### ISSUE TITLE
Error when assigning a sentry trait

### ISSUE THREAD

**Issue by Cowonapig** [jrbudda/Sentry#103]
Every time i try and assign a sentry this happens, any help would be greatly appreciated!

22:45:49 [INFO] caine238 issued server command: /sentry
22:45:56 [INFO] caine238 issued server command: /trait sentry
22:46:00 [INFO] caine238 issued server command: /trait sentry
22:46:00 [SEVERE] java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_R1/P
acket
22:46:00 [SEVERE]       at net.aufdemrand.sentry.SentryTrait.ensureInst(SentryTr
ait.java:132)
22:46:00 [SEVERE]       at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait
.java:111)
22:46:00 [SEVERE]       at net.citizensnpcs.api.npc.AbstractNPC.addTrait(Abstrac
tNPC.java:64)
22:46:00 [SEVERE]       at net.citizensnpcs.api.npc.AbstractNPC.addTrait(Abstrac
tNPC.java:44)
22:46:00 [SEVERE]       at net.citizensnpcs.commands.TraitCommands.toggle(TraitC
ommands.java:141)
22:46:00 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
22:46:00 [SEVERE]       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
22:46:00 [SEVERE]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
22:46:00 [SEVERE]       at java.lang.reflect.Method.invoke(Unknown Source)
22:46:00 [SEVERE]       at net.citizensnpcs.api.command.CommandManager.executeMe
thod(CommandManager.java:132)
22:46:00 [SEVERE]       at net.citizensnpcs.api.command.CommandManager.execute(C
ommandManager.java:87)
22:46:00 [SEVERE]       at net.citizensnpcs.api.command.CommandManager.executeSa
fe(CommandManager.java:156)
22:46:00 [SEVERE]       at net.citizensnpcs.Citizens.onCommand(Citizens.java:216
)
22:46:00 [SEVERE]       at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:44)
22:46:00 [SEVERE]       at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:186)
22:46:00 [SEVERE]       at org.bukkit.craftbukkit.v1_5_R1.CraftServer.dispatchCo
mmand(CraftServer.java:514)
22:46:00 [SEVERE]       at net.minecraft.server.v1_5_R1.PlayerConnection.handleC
ommand(PlayerConnection.java:967)
22:46:00 [SEVERE]       at net.minecraft.server.v1_5_R1.PlayerConnection.chat(Pl
ayerConnection.java:885)
22:46:00 [SEVERE]       at net.minecraft.server.v1_5_R1.PlayerConnection.a(Playe
rConnection.java:840)
22:46:00 [SEVERE]       at net.minecraft.server.v1_5_R1.Packet3Chat.handle(Packe
t3Chat.java:44)
22:46:00 [SEVERE]       at net.minecraft.server.v1_5_R1.NetworkManager.b(Network
Manager.java:292)
22:46:00 [SEVERE]       at net.minecraft.server.v1_5_R1.PlayerConnection.d(Playe
rConnection.java:113)
22:46:00 [SEVERE]       at net.minecraft.server.v1_5_R1.ServerConnection.b(Sourc
eFile:35)
22:46:00 [SEVERE]       at net.minecraft.server.v1_5_R1.DedicatedServerConnectio
n.b(SourceFile:30)
22:46:00 [SEVERE]       at net.minecraft.server.v1_5_R1.MinecraftServer.r(Minecr
aftServer.java:580)
22:46:00 [SEVERE]       at net.minecraft.server.v1_5_R1.DedicatedServer.r(Dedica
tedServer.java:225)
22:46:00 [SEVERE]       at net.minecraft.server.v1_5_R1.MinecraftServer.q(Minecr
aftServer.java:476)
22:46:00 [SEVERE]       at net.minecraft.server.v1_5_R1.MinecraftServer.run(Mine
craftServer.java:409)
22:46:00 [SEVERE]       at net.minecraft.server.v1_5_R1.ThreadServerApplication.
run(SourceFile:573)
22:46:00 [SEVERE] Caused by: java.lang.ClassNotFoundException: net.minecraft.ser
ver.v1_4_R1.Packet
22:46:00 [SEVERE]       at org.bukkit.plugin.java.PluginClassLoader.findClass0(P
luginClassLoader.java:70)
22:46:00 [SEVERE]       at org.bukkit.plugin.java.PluginClassLoader.findClass(Pl
uginClassLoader.java:53)
22:46:00 [SEVERE]       at java.lang.ClassLoader.loadClass(Unknown Source)
22:46:00 [SEVERE]       at java.lang.ClassLoader.loadClass(Unknown Source)
22:46:00 [SEVERE]       ... 29 more

**Comment by mcmonkey4eva** [comment]
It's attempting to access v1.4 features in a 1.5 server --- Update Citizens and Sentries (and all other plugins!)!

**Comment by Cowonapig** [comment]
I have tried that many times but it's still not working.

Many thanks 
Cowonapig

**Comment by XxCoolGamesxX** [comment]
Download the last: Craftbukkit and Citizen and download the last update of the sentry in the wiki of sentry. http://wiki.citizensnpcs.com/Sentry
