### ISSUE TITLE
RESPAWN and EVENT problems

### ISSUE THREAD

**Issue by uledrith** [jrbudda/Sentry#105]
If I /npc create and then /trait sentry, the mob will now die correctly since latest update. However, if I then do /sentry respawn 0, it correctly does not automatically respawn. However, I can at this point type /npc tphere and then he teleports to me and is automatically respawned (not sure if that is by design?). Now if I do the exact same thing, but --type witch instead in the beginning, and then I try to /npc tphere it says I successfully teleport the witch to me, but she is invisible. If I then do a /sentry info, it still shows the NPC as isDEAD.

Another problem I've noticed is that on the Sentry target list, EVENT:PVNPC, EVENT:PVSENTRY no longer appear to be working.

**Comment by jrbudda** [comment]
still having these problems? I tried the events today and they worked for me. the /npc tphere thing will spawn the NPC if its not spawned, so yes that's by design.

**Comment by stutiguias** [comment]
i test and EVENT:PVNPC, EVENT:PVSENTRY not work for me too

**Comment by jrbudda** [comment]
I still cannot reproduce this issue. I create a Sentry. Do /sentry target add event:pvnpc  then create another NPC and smack it and the Sentry attacks me.
