### ISSUE TITLE
Sentries sometimes spawn at wrong place

### ISSUE THREAD

**Issue by mcmonkey4eva** [jrbudda/Sentry#107]
I have sentries that spawn in a specific spot... and have no path / other data linking them back to it, other than "/sentry spawn" while they were standing there.
Then sometimes go running quite far away. (They have range 100 and pathrange 500)

Then they die... I want them to spawn back at the specified spot, which they /sometimes/ do. Other times, they spawn where they died.

Why they do this, and how do I make them always spawn correctly?

**Comment by arxenix** [comment]
Same issue here...

**Comment by mcmonkey4eva** [comment]
BTW, I'm currently using Denizen to force them to teleport to the correct location when they spawn.
It works as a temporary fix...

**Comment by jrbudda** [comment]
Trying to reproduce this and have not been able to yet. Is there a certain range beyond which they spawn where they died? Are the chunks at the spawn location loaded or unloaded at the time?

**Comment by mcmonkey4eva** [comment]
- All relevant chunks are loaded
- they're only around 50 blocks away (Chasing enemies)
- They've no path data
- enemies are still there where they died usually

**Comment by jrbudda** [comment]
Think this is a conflict with Denizen. Try sentry 1.3.6

**Comment by mcmonkey4eva** [comment]
Seeems to be fixed. Maybe. (Either from Sent1.3.6 or one of the other Cit portions I updated.)

**Comment by arxenix** [comment]
This still seems to be happening to me :/
Im on the latest Citizens and Latest Sentry. NOT using Denizens
