### ISSUE TITLE
[BUG] Sentry non-player type getting crazy

### ISSUE THREAD

**Issue by NemesisMate** [jrbudda/Sentry#108]
Zombie sentries and any other type get crazy when start attacking, when you put them like "/npc type player" they become normal again.

Using 1.3.3.3 on bukkit 1.5.1-R0.2

**Comment by jrbudda** [comment]
This is a problem in Citizens, I will pass it on to the Citizens devs.

**Comment by jrbudda** [comment]
is this fixed? i cant reproduce anymore.

**Comment by NemesisMate** [comment]
Yes, this is fixed, thanks.
