### ISSUE TITLE
[feature request] Different distances for chasing, resetting

### ISSUE THREAD

**Issue by abslodov** [jrbudda/Sentry#11]
Ok one more thing I just thought of, different distances for chasing, activating, and resetting, for example:

Let's use guarding a doorway as an example. The doorway is 2 blocks wide, and faces out to open ground that has at least 5 blocks clearance in all directions...

Logic: If I attack a sentry, he should keep attacking me until one of us dies IMO, not when I run his range in distance away and he just stops (he doesn't return to his spawn point then). OR...If I attack, he chases, and I run away until he ceases his pursuit, maybe he just should reset to his location at that point.

A sample set of values:

// Range at which sentry will activate and begin attacking it's targets
Activation range: 3
// Distance (maybe time?) the sentry will chase for before resetting. Maybe he could have variable speed and catch up to people trying to run?
Chase range: 100?

Just a thought, cheers

**Comment by jrbudda** [comment]
If you use /npc path and give him a single waypoint at his guard spot he will return to it. If his path back is blocked he will get stuck but this will be resolved in a upcoming build of citizens (he'll tp back)

**Comment by abslodov** [comment]
Right on! That's a great solution.

Also, I was wondering...will you implement pauses for waypoints? For example, I want an NPC who appears to be tinkering at his shop, walks a few paces, pauses for a while, walks somewhere else, pauses...etc..

**Comment by jrbudda** [comment]
That can be done with the Denizen WANDER activity., check out that page on the wiki.

**Comment by abslodov** [comment]
you're too kind, thanks! :]
