### ISSUE TITLE
1.3.4 not working 

### ISSUE THREAD

**Issue by coffeebuzzz** [jrbudda/Sentry#114]
Many issues,  Sentries not attacking if they have bow or projectile
cannot hard sentries, some dont issue warning, many dont attack.

some of the console errors.
Latest citizens and bukkit

1:53:51 PM
 CONSOLE:
java.lang.NoClassDefFoundError: com/massivecraft/factions/iface/RelationParticipator
1:53:51 PM
 CONSOLE:
java.lang.ClassNotFoundException: com.massivecraft.factions.iface.RelationParticipator
1:53:53 PM
 CONSOLE:
[SEVERE] Could not pass event EntityDamageByEntityEvent to Sentry v1.3.4
1:53:53 PM
 CONSOLE:
java.lang.NoClassDefFoundError: com/massivecraft/factions/iface/RelationParticipator
1:53:53 PM
 CONSOLE:
java.lang.ClassNotFoundException: com.massivecraft.factions.iface.RelationParticipator
1:53:53 PM
 CONSOLE:
[SEVERE] Could not pass event EntityDamageByEntityEvent to Sentry v1.3.4
1:53:53 PM
 CONSOLE:
java.lang.NoClassDefFoundError: com/massivecraft/factions/iface/RelationParticipator
1:53:53 PM
 CONSOLE:
java.lang.ClassNotFoundException: com.massivecraft.factions.iface.RelationParticipator
1:53:57 PM
 CONSOLE:
[INFO] coffeebuzz77 issued server command: /npc select
1:53:59 PM
 CONSOLE:
[INFO] coffeebuzz77 issued server command: /sentry info
1:53:59 PM
 CONSOLE:
[SEVERE] Could not pass event EntityDamageByEntityEvent to Sentry v1.3.4
1:53:59 PM
 CONSOLE:
java.lang.NoClassDefFoundError: com/massivecraft/factions/iface/RelationParticipator
1:53:59 PM
 CONSOLE:
java.lang.ClassNotFoundException: com.massivecraft.factions.iface.RelationParticipator

**Comment by jrbudda** [comment]
redownload it.
