### ISSUE TITLE
Group Funktion

### ISSUE THREAD

**Issue by Paul0000** [jrbudda/Sentry#115]
the group funktion doesn't work with essentrials groupmanager. Why?

**Comment by XxCoolGamesxX** [comment]
what do you mean of Group Funktion give us more info?

**Comment by Paul0000** [comment]
target one group/ignore one group (z.B. Vips)

**Comment by Paul0000** [comment]
wrong button, still open

**Comment by XxCoolGamesxX** [comment]
What are you talk ? :S

**Comment by Paul0000** [comment]
i only wanted to tell you, tht i presst Comment and Close insteat of comment and that the problem still exist.

**Comment by XxCoolGamesxX** [comment]
I not mean at but of your  issue ?

**Comment by Paul0000** [comment]
the funktion, that a sentry targets alle player from a group from a permissionsplugin doesnt work with the permissionsplugin groupmanager. When i add group:player to the target list, nothing happens.

**Comment by XxCoolGamesxX** [comment]
what permissions it you add on it ?

**Comment by Paul0000** [comment]
what do you mean?

**Comment by XxCoolGamesxX** [comment]
For me is work good the groupmanager.

**Comment by Paul0000** [comment]
whe i start the server, ther is a message that says: can register with vault, group funktion disabled.

**Comment by XxCoolGamesxX** [comment]
It you download vault plugin ?

**Comment by Paul0000** [comment]
it works, great.
