### ISSUE TITLE
Sentries murdering non-sentries

### ISSUE THREAD

**Issue by mcmonkey4eva** [jrbudda/Sentry#116]
I have some static unmoving "statue" NPC's that aren't sentry/denizen/anything... yet sometimes my stronger sentries accidentally land an arrow on it, and it somehow dies, and I have to manually respawn it.

This needs fixing.

**Comment by jrbudda** [comment]
Seemed to be a bug with the Denizen Health trait. If you can, try removing that trait from your statues. If that's not it, try it with Sentry 1.3.6 (on the wiki)

**Comment by mcmonkey4eva** [comment]
Seeems to be fixed. Maybe. (Either from Sent1.3.6 or one of the other Cit portions I updated.)
