### ISSUE TITLE
Improvement -- Drop chance percentage

### ISSUE THREAD

**Issue by coffeebuzzz** [jrbudda/Sentry#117]
Please if you can, add a percentage value we can pass into the DROP option for sentries so they will drop their items only so often.  This will make creating small dungeon bosses so much better.. especially when combined with plugins such as RPGitems.

Drop rates from 0.0 to 100.0 using any floating point such as .0001 would be ideal.

**Comment by jrbudda** [comment]
Best thing is to use Denizen to make them drop what and how you want.
