### ISSUE TITLE
Crash because of a Sentry NPC

### ISSUE THREAD

**Issue by NemesisMate** [jrbudda/Sentry#122]
I removed the sentry I modified before the last crash, it was 10-15 days ago, no more crashes (before I had them almost every day) so I am pretty sure I got this crash because of Sentry plugin: http://pastebin.com/ACYPkWMV

Before comment: http://dev.bukkit.org/server-mods/sentry-citizens2/?comment=538

**Comment by mcmonkey4eva** [comment]
Vec3D seems to be a common error for all citizens users: The Cit dev team keep refusing to make a workaround, claiming it's a bukkit error. (Bukkit says they have no intent to fix it, as they have a rule against any plugins accessing that function anyway.)

So it's kind of a stand-still ATM.

(And it's not Sentry's fault. Citizens base's fault.) (In theory.)
(That error would be a coincidence of what NPC settings are on it.) (In theory.)
(Couldn't hurt for jrbubba to make sure he doesn't call the function ever though.)

**Comment by NemesisMate** [comment]
I'm having no more crashes since time ago, I think this is fixed.
