### ISSUE TITLE
Ignore list is uh... ignored...

### ISSUE THREAD

**Issue by mcmonkey4eva** [jrbudda/Sentry#124]
I have a sniper sentry guarding an area
Target: Event:PVSentry
Ignore: entity:owner (me), player:mcmonkey4eva (also me, just to be extra safe)

When I punch a different sentry NPC nearby, the sniper fires on me.
It doesn't seem to care at all that I've asked it to ignore me.

**Comment by redacid95** [comment]
I am also having an ignore problem... I use group ignore and myself ignore, but it doesn't ignore me... It just attacks me if  i hit them...

**Comment by redacid95** [comment]
Now the default ignores aren't being set and guard are attacking eachother.

**Comment by jrbudda** [comment]
ignores will apply to event: targets in next release.
