### ISSUE TITLE
[Suggestion] Stand down command.

### ISSUE THREAD

**Issue by redacid95** [jrbudda/Sentry#126]
There should be groups you can set up the sentries/ guards in and then with one command you can have all the guards in one group stop targeting people and with another command you can have them reactivate with their normal targets. This will help with RPG servers. I use sentries to guard my castle and if I want to allow people not normally allowed to visit, I have to change each individual castle guard's target list.

**Comment by mcmonkey4eva** [comment]
Uh... slight change to what you're suggesting, but I believe it's your intent or at least similar:

A sentry group option, where all sentries in the group share a target/ignore list.

I would love that!

(Also, a command to completely stop attacking anything, as seems to be how you wanted it in your post. - not useful to me as much as what I said above, but it is a good idea too.)

**Comment by jrbudda** [comment]
a better solution to your original problem instead of changing each sentries' targets, just give them a GROUP: target and add/remove players from the group as needed.

**Comment by redacid95** [comment]
See that is why you are the creator, you find good solutions that require no extra coding.
