### ISSUE TITLE
Default ignore list isn't working.

### ISSUE THREAD

**Issue by redacid95** [jrbudda/Sentry#131]
First off the ignore list for new NPCs that I create is empty but it has its default targets.
Second the NPCs attack each other unless I tell them to ignore entity:NPC
Third the ignore groups does not work it will attack anything against its directives (I will get attacked even if I am ignored and do an event:pvp around them)
Fourth Even ignoring owners wont work unless they are bodyguards.

**Comment by fatalisslayer22** [comment]
i dont get this issue but try re-downloading the plugin, and make sure you use your codes right like if you want them to atk npc or atk real players, maybe you have commands that conflict with one another 

ex. npc will atk mobs but another says to atk players, conflict with what it should and shouldt atk

**Comment by redacid95** [comment]
I've done this already.

**Comment by jrbudda** [comment]
Seems I left off the quotes in the commented-out lines in the config.yml
try it like this

DefaultIgnores:
- "entity:NPC"

**Comment by redacid95** [comment]
I did that to fix the ignore for the NPC and it worked, but the ignore group doesn't work and they will still attack. The only time group ignore works is if they are guarding a specific player.

**Comment by jrbudda** [comment]
Sentry 1.3.7+ should fix the ignores not applying to event: targets.
