### ISSUE TITLE
Have projectiles go through NPCs

### ISSUE THREAD

**Issue by stvncao5** [jrbudda/Sentry#133]
If a sentry fires an arrow or any other projectile, it should go through every entity unless the entity is a:

Target.
Or on the target list.

There's a few reasons as to why this idea should be implemented, for example:
- A guard who's supposed to one-hit people via shooting at them could kill an innocent bystander in one hit. Scary!
- Let's face it, no one likes friendly fire that doesn't come from explosions or fire. Players under friendly fire are okay, because players are (presumably) smart enough to move so as not to hit their friends. NPCs aren't that smart.
- A group of archers will never work. They'll all start killing each other. Yes, I know I can use line formations, but that's tedious. And when they all break line formation by following a target, they clump.
- A player can lure an NPC into killing other entities they shouldn't be killing.
- Players don't have to worry about getting in the way of their bodyguard.
- Something else I haven't thought of.

If having projectiles go through NPCs is unfeasible, you could always find some other sort of ingenious solution... Maybe canceling the projectile completely when it doesn't hit its intended target. (That has one caveat of creating human shields and rendering archer groups useless.)

**Comment by jrbudda** [comment]
This isn't really possible, projectile collision is handled in minecraft and manually messing with each projectile hit to see if it hit the 'right' target is not something I'd really like to do. Players can friendly fire each other, and so can mobs, so I think sentries should too.

If I can think of an elegant solution I may try to implement something.

**Comment by stvncao5** [comment]
I thought it was possible, or at least for mobs, because I saw a plugin called "ExtraHardMode" allow arrows to pass through skeletons, or something of that nature.

I see your point, but realise that players are smart enough to move out of the way when friendly fire happens. Mobs... well they're mobs, I don't really see a point in ceasing friendly fire for them.

Sentries, on the other hand, aren't smart enough to "get out of the way" when getting hit by an ally sentry. In other words, either make the AI smarter in handling friendly fire, or disable friendly fire for sentries. Maybe instead of handling the projectile collision itself, you could handle the damage dealt, where in the case of friendly fire, the damage defaults to 0.

As for the sentry's AI when handling friendly fire, one really basic (but clunky) solution would be to have the sentry move to a nearby position that isn't within the "offending" sentry's line-of-sight.

**Comment by jrbudda** [comment]
I'll take a look at that plugin.

**Comment by jrbudda** [comment]
It's ugly but I think I can make this work.
