### ISSUE TITLE
That command must be performed on a Sentry!

### ISSUE THREAD

**Issue by DaEmonX555** [jrbudda/Sentry#139]
I have selected the sentry and try to use /sentry region 5   but it gives e this mesage That command must be performed on a Sentry!

**Comment by mcmonkey4eva** [comment]
Make sure you first set /trait sentry

**Comment by jrbudda** [comment]
/sentry region is not a valid command... what are you trying to do?

**Comment by DaEmonX555** [comment]
/sentry range.... auto-correct got me at 2am
