### ISSUE TITLE
Non-player Citizens disappearing

### ISSUE THREAD

**Issue by NemesisMate** [jrbudda/Sentry#140]
I can't report this to Citizens devs because it says me that "my JIRAs evaluation period has expired", maybe you can do it because this affects to Sentry too:

If you set a NPC like a wither skeleton, a baby zombie, etc, them disappear if you go out from him and come back, for example teleporting.

**Comment by mythan** [comment]
Yes, I've experienced too. I have to change their "npc type" back to "player" for them to become visible again.

**Comment by jrbudda** [comment]
I will bring this up to the citizens dev if its still an issue.
