### ISSUE TITLE
target "entity:player" function not working!

### ISSUE THREAD

**Issue by vfhnbhjvhggh** [jrbudda/Sentry#149]
After updating both citizens and sentry, it appears there is a problem with one of the two plugins (or both) however I suspect the issue lies within Sentry, as Citizens seems to be working properly. 

When setting a sentries target to entity:player, the npc will acknowledge the presence of a player within its range, however will not function the way it's suppose to (referring to all previous versions)  
... 

It will proceed to jump continuously and, walk in random directions; usually jumping into walls. If you're to get close enough into attacking distance it will attack and can be attacked its self. This gives reason to believe that it's the sentries target entity:player which is the issue. 

I am very familiar with Sentry and this has never happened before until the 1.6.2 update.
Seeming there are no other complaints about this, perhaps it is just me - or maybe not. 

Can someone please explain if this is a common issue or, how to resolve it?
thank you, vfhnbhjvhggh

**Comment by jrbudda** [comment]
Go into the Citizens config.yml and change the setting 'use-new-pathfinder' to false.

Future versions of sentry will disable this automatically, it'd quite buggy.

**Comment by vfhnbhjvhggh** [comment]
Ah! Beautiful! 
Thank you very much (:
