### ISSUE TITLE
Sentry wont attack anything

### ISSUE THREAD

**Issue by ghost** [jrbudda/Sentry#15]
Here is the list of commands i use

/npc create test1 --trait sentry
/sentry guard
/sentry target add zombie

i spawn zombie and nothing happens

**Comment by jrbudda** [comment]
/sentry target add entity:zombie

Are there instructions somewhere saying you can just use zombie?

**Comment by ghost** [comment]
yes but that method also gives me no results.

**Comment by jrbudda** [comment]
Where does it say you can use just zombie? it needs to be changed.
/sentry target add entity:zombie
works, i just tried it.

**Comment by ghost** [comment]
http://www.youtube.com/watch?v=75pYrGlIcFs its a video by aufdemrand. I realize that video might be old. But none the less that is the biggest problem it seems to be working for everyone but me. Also if you look on forums another guy posted the same error 6 hours ago.
http://dev.bukkit.org/server-mods/citizens/forum/42636-sentries-wont-attack/#p5

**Comment by ghost** [comment]
hmm weird. Reinstalling Bukkit fully, then installing plugins again seemed to have fixed the problem but now sometimes when I spawn an npc it turns out to be fully black with no textures :S Thank you for your time!

**Comment by jrbudda** [comment]
Ah the video, yea that is way out of date.
I cannot reproduce this problem. Using latest versions of Citizens 2 and Senty:
/npc create Guard --trait sentry
/npc target add entity:zombie

Spawn a zombie within a few blocks and he goes to town on it

**Comment by jrbudda** [comment]
Oh ok, strange. Glad its working for you.
Did you name you NPC 'test' ? That npc name comes with a totally black skin.

**Comment by ghost** [comment]
Ahh!! that is it. I did name it test. Thank you very much sir.
