### ISSUE TITLE
Lag and jumping alot

### ISSUE THREAD

**Issue by Darius013** [jrbudda/Sentry#150]
So I've created 2 NPCs with trait sentry and when they fight they jump alot and lags my server I go from 20 Ticks to 15 Ticks when they fight.

I'm using the latest files for citizens2, sentry and craftbukkit.

PD: They are jumping everytime and looks like they're retarded looking around, jumping and even doing damage.

**Comment by jrbudda** [comment]
in the citizens config.yml set 'use-new-pathfinder' to false

It's buggy.

**Comment by Darius013** [comment]
Thanks dude it helped me alot!
