### ISSUE TITLE
Sentry Pathing Lag - Server Crawl

### ISSUE THREAD

**Issue by Crazdale** [jrbudda/Sentry#152]
So, after using Sentry today, I've noticed a huge bug with the pathing.  When a Sentry stops, for such actions as, looking at a hostile mob it would like to attack on a roof, but cannot reach, or staring at a zombie on the other side of a fence, whatever the cause, whenever a Sentry is halted in its path, and does not move for a few seconds, it causes some SEVERE server lag.  I mean, just about halts our server to a crawl.  Seems like the pathing waypoints continue on and queue up until all the resources are used up... I dunno.

Anyways, when you fix what is holding up the Sentry pathing (killing at mob they stopped to stare at, etc.), server performance returns to normal... these NPC's just cannot stop though, without causing some serious problems.

**Comment by jrbudda** [comment]
in the citizens config.yml set use-new-pathfinder to false, it's buggy. Future versions of sentry disable is by default.

**Comment by Crazdale** [comment]
Thank you jrbudda ;)
