### ISSUE TITLE
NPCs Will Not Attack

### ISSUE THREAD

**Issue by RFSMassacre** [jrbudda/Sentry#153]
I've been trying to get NPCs to attack players upon seeing them and I added "entity:player" to the target list like it's supposed to but it just won't attack players unless attacked first. I even tried by having "entity:all" but it continued to do the same thing. The only time they attack something first is if it's a mob. Is there anything I could do to fix this?

**Comment by jrbudda** [comment]
entity:player is working normally for me, is there anything on that Sentries ignore list? What version of Sentry/Craftbukkit are you using?

**Comment by RFSMassacre** [comment]
I'm using the latest version of Craftbukkit, Sentry, and Citizens. Even when I updated them to the latest version the NPCs still don't attack. The sentries don't have anything on the ignore list. I only have one sentry with "entity:player" for target, and "entity:mob" for ignore but it only attacks mobs first. You'd have to hit him for him to fight.

**Comment by jrbudda** [comment]
hmm that's a head scratcher. I'm using the same as you. I do:
/npc create Guard --trait sentry
/sentry target add entity:player
and he immediately starts attacking me.
Only thing I can think of is maybe some weird plugin conflict?

**Comment by RFSMassacre** [comment]
Here's what I have installed:

HorseCraftables, Referrals, WorldEdit, NoCheatPlus, PluginManager, AntiXRay, mcore, CVault, AutoSaver, PEX, LoginSecurity, Votifier, SleepVote, MobArena, GAListerner, Essentials, Factions, UltimateArena, LiveChat, EssentialsSpawn, CustomSpawners, Citizens, Sentry, and mcMMO.

Is there a known plugin conflict with Citizens+Sentry with any of these plugins?

**Comment by jrbudda** [comment]
Not a known conflict, but just for grins can you try starting up with only Citizens and Sentry and see if it still does it?

**Comment by RFSMassacre** [comment]
I've removed all plugins and ran nothing but Citizens+Sentry and the problem is still there. It works for a good ten minutes but then they stop warning and stop attacking after that and ignore you until you hit them. I use them for bosses in the dungeons on my server and I really need the sentries to be hostile as soon as you get near them.

Is there anything else I can do?

**Comment by RFSMassacre** [comment]
I also made sure that the new pathfinder was set to false since I know it causes problems for most people, but the sentries still do not attack players.

**Comment by jrbudda** [comment]
so they work normally for 10 minutes?

**Comment by RFSMassacre** [comment]
Yeah, it only works normally for the first ten minutes of enabling Citizens and Sentry, but then the NPCs stop attacking.

**Comment by jrbudda** [comment]
Well that thickens the plot quite a bit.... I have no idea. can you pastebin me your citizens saves.yml? I'll try to duplicate your sentries more exactly.

**Comment by RFSMassacre** [comment]
Here's the saves file for Citizens.

http://pastebin.com/KNZivLxv

I also want to thank you for taking the time to help me out. The players on my server love the plugin and the ability to fight more than just the two original bosses.

**Comment by OokamiNex** [comment]
I'm having the same issue more or less, Only thing I'm running is citizens and Sentry. They won't attack unless they're attacked first. can't even get them to attack mobs. Gives me Errors as soon as I use /trait sentry, but gives the NPC the trait anyways.

**Comment by OokamiNex** [comment]
Java.Lang.NoSuchMethodError:
net.citizensnpcs.api.npc.NPC.teleport(Lorg/bukkit/Location;Lorg/bukkit/event/player/PlayerTeleportEvent$TeleportCause;)V is what I get

**Comment by RFSMassacre** [comment]
Have you given them the target to attack players? To do that you make them a sentry then run the command: 

/sentry target add entity:player

This will make them attack players right away, however my problem is that they don't attack them even with the target set.

**Comment by jrbudda** [comment]
update citizens.

**Comment by OokamiNex** [comment]
The problem seems to be with citizens. when downloading it, go to latest stable mod, my partner went with the latest build, which isn't on the top of the screen. it's two down from the one I think everyones downloading.
Thank you for your time jrBudda and RFS. cheers

**Comment by vfhnbhjvhggh** [comment]
I am having the same issues as well - could you please give a link from where to download the build? 
Thanks (:

@OokamiNex

**Comment by jrbudda** [comment]
http://ci.citizensnpcs.com/job/Citizens2/

**Comment by vfhnbhjvhggh** [comment]
Okay so I checked to see if this was a plugin compatibility issue; it seems that SpoutPlugin affects npc's quite a lot!
I'm not sure if this is citizens or sentry.

once i removed Spout everything was working... for a few minutes... 
I had downloaded the new files and replaced the old... 
_sigh_
