### ISSUE TITLE
CANT GET SENTRY TO MOUNT HORSE!

### ISSUE THREAD

**Issue by kingsean24** [jrbudda/Sentry#155]
when i use /sentry mount it just says /sentry help -_- HELP?!?!?!?!

**Comment by jrbudda** [comment]
What version are you using?

**Comment by kingsean24** [comment]
let me check

**Comment by kingsean24** [comment]
1.4.1 for sentry

**Comment by jrbudda** [comment]
Mounts were added in Sentry 1.5

**Comment by kingsean24** [comment]
one sec...

**Comment by kingsean24** [comment]
well that was embarrising TY byez

**Comment by kingsean24** [comment]
okay now can i get armor on the horse?

**Comment by kingsean24** [comment]
nvm

**Comment by jrbudda** [comment]
I think theres some issues yet with equipping a horse NPC, should be fixed in future version of Citizens.
