### ISSUE TITLE
Website Wiki Down!

### ISSUE THREAD

**Issue by GiuseppeGroth** [jrbudda/Sentry#156]
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, root@wg.sk and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

**Comment by XxCoolGamesxX** [comment]
The Wiki is up here the link: http://wiki.citizensnpcs.co/Sentry
