### ISSUE TITLE
Exception on setting sentry trait

### ISSUE THREAD

**Issue by NoArmsNoCookies** [jrbudda/Sentry#157]
Hi,

I just updated to the lastest Bukkit (CraftBukkit 1.6.2-R0.1), Citizen2 (build 912) and Sentry (v.1.5.1), and I get an exception each time i add the sentry trait to an npc. However the sentry seems to work. I also get an exception for the first npc with sentry trait when restarting the server (see below).

---

23:10:53 Citizens: Loading Citizens v2.0.9-SNAPSHOT (build 912)
23:10:53 Sentry: Loading Sentry v1.5.1
23:10:53 dtlTraders: Loading dtlTraders v3.0.3 Beta
23:10:53 Blacksmith: Loading Blacksmith v1.1

---

23:16:54 CONSOLE: [INFO] NoArmsNoCookies issued server command: /trait sentry
23:16:54 CONSOLE: [SEVERE] java.lang.NoSuchMethodError: net.citizensnpcs.api.npc.NPC.teleport(Lorg/bukkit/Location;Lorg/bukkit/event/player/PlayerTeleportEvent$TeleportCause;)V
23:16:54 CONSOLE: [SEVERE] at net.aufdemrand.sentry.SentryInstance.initialize(SentryInstance.java:990)
23:16:54 CONSOLE: [SEVERE] at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:128)
23:16:54 CONSOLE: [SEVERE] at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:71)
23:16:54 CONSOLE: [SEVERE] at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:50)
23:16:54 CONSOLE: [SEVERE] at net.citizensnpcs.commands.TraitCommands.toggle(TraitCommands.java:141)
23:16:54 CONSOLE: [SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:16:54 CONSOLE: [SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
23:16:54 CONSOLE: [SEVERE] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
23:16:54 CONSOLE: [SEVERE] at java.lang.reflect.Method.invoke(Unknown Source)
23:16:54 CONSOLE: [SEVERE] at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:131)
23:16:54 CONSOLE: [SEVERE] at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:86)
23:16:54 CONSOLE: [SEVERE] at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:155)
23:16:54 CONSOLE: [SEVERE] at net.citizensnpcs.Citizens.onCommand(Citizens.java:214)
23:16:54 CONSOLE: [SEVERE] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
23:16:54 CONSOLE: [SEVERE] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:191)
23:16:54 CONSOLE: [SEVERE] at org.bukkit.craftbukkit.v1_6_R2.CraftServer.dispatchCommand(CraftServer.java:523)
23:16:54 CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R2.PlayerConnection.handleCommand(PlayerConnection.java:962)
23:16:54 CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R2.PlayerConnection.chat(PlayerConnection.java:880)
23:16:54 CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R2.PlayerConnection.a(PlayerConnection.java:837)
23:16:54 CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R2.Packet3Chat.handle(SourceFile:49)
23:16:54 CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R2.NetworkManager.b(NetworkManager.java:296)
23:16:54 CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R2.PlayerConnection.e(PlayerConnection.java:116)
23:16:54 CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R2.ServerConnection.b(SourceFile:37)
23:16:54 CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R2.DedicatedServerConnection.b(SourceFile:30)
23:16:54 CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:590)
23:16:54 CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226)
23:16:54 CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)
23:16:54 CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419)
23:16:54 CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)

---

And on restarting the server I get:

---

23:38:04 Sentry: Registered sucessfully with Vault: 5 groups found. The GROUP: target will function
23:38:04 CONSOLE: [SEVERE] [Citizens] An exception occurred while the trait sentry was spawning for NPC ID 19.
23:38:04 CONSOLE: [SEVERE] java.lang.NoSuchMethodError: net.citizensnpcs.api.npc.NPC.teleport(Lorg/bukkit/Location;Lorg/bukkit/event/player/PlayerTeleportEvent$TeleportCause;)V
23:38:04 CONSOLE: [SEVERE] at net.aufdemrand.sentry.SentryInstance.initialize(SentryInstance.java:990)
23:38:04 CONSOLE: [SEVERE] at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:128)
23:38:04 CONSOLE: [SEVERE] at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:220)
23:38:04 CONSOLE: [SEVERE] at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:137)
23:38:04 CONSOLE: [SEVERE] at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:55)
23:38:04 CONSOLE: [SEVERE] at net.citizensnpcs.Citizens$1.run(Citizens.java:273)
23:38:04 CONSOLE: [SEVERE] at org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftTask.run(CraftTask.java:53)
23:38:04 CONSOLE: [SEVERE] at org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
23:38:04 CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:522)
23:38:04 CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226)
23:38:04 CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)
23:38:04 CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419)
23:38:04 CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
23:38:04 CONSOLE: [SEVERE] [Citizens] An exception occurred while the trait sentry was spawning for NPC ID 21.
23:38:04 CONSOLE: [SEVERE] java.lang.NoSuchMethodError: net.citizensnpcs.api.npc.NPC.teleport(Lorg/bukkit/Location;Lorg/bukkit/event/player/PlayerTeleportEvent$TeleportCause;)V
23:38:04 CONSOLE: [SEVERE] at net.aufdemrand.sentry.SentryInstance.initialize(SentryInstance.java:990)
23:38:04 CONSOLE: [SEVERE] at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:128)
23:38:04 CONSOLE: [SEVERE] at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:220)
23:38:04 CONSOLE: [SEVERE] at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:137)
23:38:04 CONSOLE: [SEVERE] at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:55)
23:38:04 CONSOLE: [SEVERE] at net.citizensnpcs.Citizens$1.run(Citizens.java:273)
23:38:04 CONSOLE: [SEVERE] at org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftTask.run(CraftTask.java:53)
23:38:04 CONSOLE: [SEVERE] at org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
23:38:04 CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:522)
23:38:04 CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226)
23:38:04 CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)
23:38:04 CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419)
23:38:04 CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
23:38:04 Citizens: Loaded 20 NPCs.

**Comment by OokamiNex** [comment]
Same Issue here

**Comment by drogersonco** [comment]
Same issue here.  I have updated and reinstalled.  getting same error messages.

**Comment by mcmonkey4eva** [comment]
@NoArmsNoCookies @OokamiNex @drogersonco - If you're still having issues, update your Citizens from this link:
http://ci.citizensnpcs.co/job/Citizens2/
(Dev builds)

**Comment by drogersonco** [comment]
Same issue no matter the update.  keep updating hoping the problem will be fixed.  updated again today.  same error.   If I remove sentry completely the error goes away.  Once I reinstall it comes back.

**Comment by jrbudda** [comment]
Make sure you are on the latest DEV build of citizens (build 977 as I write this), and the latest Sentry, 1.5.2

Also make sure that you do not have multiple citizens or Sentry jars in your plugins folder.

**Comment by drogersonco** [comment]
I am.  That is what makes this so confusing.  I have removed everything to
do with sentry and my server runs brilliantly, add it back it boom, same
error messages.  Not only do I get the error messages but the sentry's will
not behave like sentry's.  It doesn't matter what I change or don't
change.  Only the citizens2 npc commands work on them.

Until next time,

DeAnna

**Comment by mcmonkey4eva** [comment]
@drogersonco - Are you updating Citizens2 from BukkitDev, or from here: http://ci.citizensnpcs.co/job/Citizens2/ ?

**Comment by drogersonco** [comment]
http://ci.citizensnpcs.co/job/Citizens2/  I tried #977 this morning.  no
improvement

Until next time,

DeAnna

**Comment by mcmonkey4eva** [comment]
@drogersonco - Can you copy/paste the error you received? The error in the OP is _definitely_ just an outdated Citizens... yours might look the same, but it can't be exactly the same (Unless you have two copies of Cit or something)

**Comment by drogersonco** [comment]
I will do that for you tomorrow, have to get kids to their soccer games.
Thank you for your prompt responses.  Really would like to get this worked
out.  Thanks.

Until next time,

DeAnna

**Comment by drogersonco** [comment]
Good morning

Alright -- I am running Craftbukkit 1.6.2-R1.0 build #2879 on a
Multicraft-Beastnode server
Sentry 1.5.2  loaded #977 yesterday and Citzens v2.09. #912

Below is the error I get on server start up

19.09 11:07:55 [Server] INFO Loaded 14 NPCs.
19.09 11:07:55 [Server] SEVERE at
net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
19.09 11:07:55 [Server] SEVERE at
net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419)
19.09 11:07:55 [Server] SEVERE at
net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)
19.09 11:07:55 [Server] SEVERE at
net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226)
19.09 11:07:55 [Server] SEVERE at
net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:522)
19.09 11:07:55 [Server] SEVERE at
org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345)
19.09 11:07:55 [Server] SEVERE at
org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftTask.run(CraftTask.java:53)
19.09 11:07:55 [Server] SEVERE at
net.citizensnpcs.Citizens$1.run(Citizens.java:273)
19.09 11:07:55 [Server] SEVERE at
net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:55)
19.09 11:07:55 [Server] SEVERE at
net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:137)
19.09 11:07:55 [Server] SEVERE at
net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:220)
19.09 11:07:55 [Server] SEVERE at
net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:127)
19.09 11:07:55 [Server] SEVERE at
net.aufdemrand.sentry.SentryInstance.initialize(SentryInstance.java:1008)
19.09 11:07:55 [Server] SEVERE java.lang.NoSuchMethodError:
net.citizensnpcs.api.npc.NPC.teleport(Lorg/bukkit/Location;Lorg/bukkit/event/player/PlayerTeleportEvent$TeleportCause;)V
19.09 11:07:55 [Server] SEVERE An exception occurred while the trait sentry
was spawning for NPC ID 32.
19.09 11:07:55 [Server] INFO Registered sucessfully with Vault: 5 groups
found. The GROUP: target will function
19.09 11:07:54 [Server] INFO GroupManager - INFO - Bukkit Permissions
Updated!
19.09 11:07:54 [Server] Startup Done (4.997s)! For help, type "help" or "?"
19.09 11:07:54 [Server] INFO Server permissions file permissions.yml is
empty, ignoring it
19.09 11:07:54 [Server] INFO v1.1 enabled.
19.09 11:07:54 [Server] INFO Enabling Blacksmith v1.1
19.09 11:07:54 [Server] INFO Enabling EssentialsAntiBuild v2.11.1
19.09 11:07:54 [Server] INFO Enabling EssentialsChat v2.11.1
19.09 11:07:54 [Server] INFO v1.1 enabled.
19.09 11:07:54 [Server] INFO Enabling Alchemist v1.1
19.09 11:07:54 [Server] INFO Could not find or register with SimpleClans.
19.09 11:07:54 [Server] INFO Registered with War sucessfully. The TEAM:
target will function
19.09 11:07:54 [Server] INFO Could not find or register with Factions.
19.09 11:07:54 [Server] INFO Could not find or register with Towny
19.09 11:07:54 [Server] INFO Could not register with Denizen
19.09 11:07:54 [Server] INFO Enabling Sentry v1.5.2
19.09 11:07:54 [Server] INFO Enabling EssentialsSpawn v2.11.1
19.09 11:07:54 [Server] INFO Enabling EssentialsProtect v2.11.1
19.09 11:07:53 [Server] INFO Enabling Citizens v2.0.9-SNAPSHOT (build 912)

When I attempt to create and assign an NPC --trait sentry  I get the below
error on screen

Please report this error:[seeconsole]
jave.lang.NoSuchMethodError:net.citizensnpcs.api.npc.NPC.teleport(Lorg/bukkit/Location:Lorg/bukkit/event/player/PlayerTeleportEvent$TeleportCause:)V

Now back to the Console, this is the error from the console

19.09 11:18:48 [Server] SEVERE at
net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:131)
19.09 11:18:48 [Server] SEVERE at java.lang.reflect.Method.invoke(Unknown
Source)
19.09 11:18:48 [Server] SEVERE at
sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
19.09 11:18:48 [Server] SEVERE at
sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
19.09 11:18:48 [Server] SEVERE at
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19.09 11:18:48 [Server] SEVERE at
net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:355)
19.09 11:18:48 [Server] SEVERE at
net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:71)
19.09 11:18:48 [Server] SEVERE at
net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:127)
19.09 11:18:48 [Server] SEVERE at
net.aufdemrand.sentry.SentryInstance.initialize(SentryInstance.java:1008)
19.09 11:18:48 [Server] SEVERE java.lang.NoSuchMethodError:
net.citizensnpcs.api.npc.NPC.teleport(Lorg/bukkit/Location;Lorg/bukkit/event/player/PlayerTeleportEvent$TeleportCause;)V
19.09 11:17:53 [Server] INFO CONSOLE: Save complete.
19.09 11:17:53 [Server] INFO CONSOLE: Forcing save..
19.09 11:17:53 [Server] INFO CONSOLE: Enabled level saving..
19.09 11:17:53 [Multicraft] Auto-saving world...
19.09 11:17:44 [Server] INFO Players: Master MzRogers
19.09 11:17:04 [Server] SEVERE at
net.minecraft.server.v1_6_R2.ThreadServerApplication.run(SourceFile:582)
19.09 11:17:04 [Server] SEVERE at
net.minecraft.server.v1_6_R2.MinecraftServer.run(MinecraftServer.java:419)
19.09 11:17:04 [Server] SEVERE at
net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)
19.09 11:17:04 [Server] SEVERE at
net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226)
19.09 11:17:04 [Server] SEVERE at
net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:529)
19.09 11:17:04 [Server] SEVERE at
org.bukkit.craftbukkit.v1_6_R2.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
19.09 11:17:04 [Server] SEVERE at
org.bukkit.craftbukkit.v1_6_R2.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:287)
19.09 11:17:04 [Server] SEVERE at
org.bukkit.craftbukkit.v1_6_R2.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:179)
19.09 11:17:04 [Server] SEVERE at
org.bukkit.craftbukkit.v1_6_R2.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:13)
19.09 11:17:04 [Server] SEVERE at
org.bukkit.craftbukkit.v1_6_R2.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:58)
19.09 11:17:04 [Server] SEVERE at
org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
19.09 11:17:04 [Server] SEVERE at
org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
19.09 11:17:04 [Server] SEVERE at
org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
19.09 11:17:04 [Server] SEVERE at
org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
19.09 11:17:04 [Server] SEVERE at java.lang.reflect.Method.invoke(Unknown
Source)
19.09 11:17:04 [Server] SEVERE at
sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
19.09 11:17:04 [Server] SEVERE at
sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
19.09 11:17:04 [Server] SEVERE at
net.citizensnpcs.EventListen.onChunkLoad(EventListen.java:106)
19.09 11:17:04 [Server] SEVERE at
net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:311)
19.09 11:17:04 [Server] SEVERE at
net.citizensnpcs.EventListen.spawn(EventListen.java:328)
19.09 11:17:04 [Server] SEVERE at
net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:220)
19.09 11:17:04 [Server] SEVERE at
net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:127)
19.09 11:17:04 [Server] SEVERE at
net.aufdemrand.sentry.SentryInstance.initialize(SentryInstance.java:1008)
19.09 11:17:04 [Server] SEVERE java.lang.NoSuchMethodError:
net.citizensnpcs.api.npc.NPC.teleport(Lorg/bukkit/Location;Lorg/bukkit/event/player/PlayerTeleportEvent$TeleportCause;)V
19.09 11:17:04 [Server] SEVERE An exception occurred while the trait sentry
was spawning for NPC ID 32.

Please note that I have notices that the NPC error at start up will vary.
It isn't the same NPC id.  I played with that to see if it was one specific
NPC that was misbehaving and causing trouble.  But it doesn't seem to
matter if I delete them, recreate them or even just create a generic NPC

Please let me know if I can provide anything else, what I might be doing
wrong, provide this in a better format for you?

Just doubled checked that I have
one- sentry readme.txt
one - sentry.jar
one - citizens.jar
one - sentry folder - containing one config.yml file
one - citizens folder - containing one lang folder one config.yml and one
saves.yml

That's all I can think of to give you.  Anything else?

Until next time,

DeAnna

**Comment by jrbudda** [comment]
That error can only be coming from using a build of Citizens prior to #940, are you using 912 or 977? Try 977 again. Make sure you fully stop your server when replacing plugins.

http://ci.citizensnpcs.co/job/Citizens2/977/

**Comment by drogersonco** [comment]
Yes I am.  That is the one I put on the server yesterday.   and I always
stop the server.  any other ideas?

Until next time,

DeAnna

**Comment by drogersonco** [comment]
Oh and in case I didn't mention it I have even tried a complete
re-install.  Removing all sentry items and all citizens2 items and
reinstalling.  same thing

Until next time,

DeAnna

**Comment by drogersonco** [comment]
I will try a process of elimination.  will try one more time.  I will
remove everything to do with sentry and citizens even from permissions,
groups, players, etc.  everything.  then I will install citizens2 first,
then begin to add from there and see if it changes anything.  Maybe
something was hanging around where it should'nt be.  phew.  lets hope this
works!

Until next time,

DeAnna

**Comment by mcmonkey4eva** [comment]
@drogersonco - There's no way you can receive that error with Citizens up-to-date.

If your process of elimination plan doesn't come up with anything:
Join our two IRCs at http://webchat.esper.net/?channels=citizens,denizen-dev
And ask somebody trustworthy (Anybody with an @ or + in front of their name) to check out your server, possibly giving them (Temporary!) access to FTP.
(If you do this, remember to fully backup your server, don't give them account control, and ensure the password they access it under is a temporary one, changed after you're done. Gotta be careful, even when you explicitly choose a trustworthy user)

**Comment by drogersonco** [comment]
Yesterday deleted everything to do with Citizens 2, blacksmith, sentry, etc
Restarted server after each delete to make sure it was gone.  (that I
hadn't done before, would just delete citizens2 and sentry, restart,
reinstall and move on)  Reinstalled each one independently and restarted
after each one to ensure it was working at each step of the way.  That
worked.  Something like you say and old something must have been hanging
around.  Thanks for your time.

Until next time,

DeAnna
