### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by Bydon** [jrbudda/Sentry#158]
02:08:59 [INFO] [Sentry] Registered sucessfully with Vault: 7 groups found. The
GROUP: target will function
02:08:59 [SEVERE] [Citizens] An exception occurred while the trait sentry was sp
awning for NPC ID 6.
02:08:59 [SEVERE] java.lang.NoSuchMethodError: net.citizensnpcs.api.npc.NPC.tele
port(Lorg/bukkit/Location;Lorg/bukkit/event/player/PlayerTeleportEvent$TeleportC
ause;)V
02:08:59 [SEVERE]       at net.aufdemrand.sentry.SentryInstance.initialize(Sentr
yInstance.java:990)
02:08:59 [SEVERE]       at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait
.java:128)
02:08:59 [SEVERE]       at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.ja
va:220)
02:08:59 [SEVERE]       at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.jav
a:137)
02:08:59 [SEVERE]       at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(
SimpleNPCDataStore.java:55)
02:08:59 [SEVERE]       at net.citizensnpcs.Citizens$1.run(Citizens.java:273)
02:08:59 [SEVERE]       at org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftTask.ru
n(CraftTask.java:53)
02:08:59 [SEVERE]       at org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftSchedul
er.mainThreadHeartbeat(CraftScheduler.java:345)
02:08:59 [SEVERE]       at net.minecraft.server.v1_6_R2.MinecraftServer.t(Minecr
aftServer.java:522)
02:08:59 [SEVERE]       at net.minecraft.server.v1_6_R2.DedicatedServer.t(Dedica
tedServer.java:226)
02:08:59 [SEVERE]       at net.minecraft.server.v1_6_R2.MinecraftServer.s(Minecr
aftServer.java:486)
02:08:59 [SEVERE]       at net.minecraft.server.v1_6_R2.MinecraftServer.run(Mine
craftServer.java:419)
02:08:59 [SEVERE]       at net.minecraft.server.v1_6_R2.ThreadServerApplication.
run(SourceFile:582)
02:08:59 [SEVERE] [Citizens] An exception occurred while the trait sentry was sp
awning for NPC ID 7.
02:08:59 [SEVERE] java.lang.NoSuchMethodError: net.citizensnpcs.api.npc.NPC.tele
port(Lorg/bukkit/Location;Lorg/bukkit/event/player/PlayerTeleportEvent$TeleportC
ause;)V
02:08:59 [SEVERE]       at net.aufdemrand.sentry.SentryInstance.initialize(Sentr
yInstance.java:990)
02:08:59 [SEVERE]       at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait
.java:128)
02:08:59 [SEVERE]       at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.ja
va:220)
02:08:59 [SEVERE]       at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.jav
a:137)
02:08:59 [SEVERE]       at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(
SimpleNPCDataStore.java:55)
02:08:59 [SEVERE]       at net.citizensnpcs.Citizens$1.run(Citizens.java:273)
02:08:59 [SEVERE]       at org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftTask.ru
n(CraftTask.java:53)
02:08:59 [SEVERE]       at org.bukkit.craftbukkit.v1_6_R2.scheduler.CraftSchedul
er.mainThreadHeartbeat(CraftScheduler.java:345)
02:08:59 [SEVERE]       at net.minecraft.server.v1_6_R2.MinecraftServer.t(Minecr
aftServer.java:522)
02:08:59 [SEVERE]       at net.minecraft.server.v1_6_R2.DedicatedServer.t(Dedica
tedServer.java:226)
02:08:59 [SEVERE]       at net.minecraft.server.v1_6_R2.MinecraftServer.s(Minecr
aftServer.java:486)
02:08:59 [SEVERE]       at net.minecraft.server.v1_6_R2.MinecraftServer.run(Mine
craftServer.java:419)
02:08:59 [SEVERE]       at net.minecraft.server.v1_6_R2.ThreadServerApplication.
run(SourceFile:582)

Also happens when creating new ones, those already existed

**Comment by jrbudda** [comment]
update citizens
http://ci.citizensnpcs.com/job/Citizens2/
