### ISSUE TITLE
Npc Location Save

### ISSUE THREAD

**Issue by White-Arrow** [jrbudda/Sentry#159]
when i try to use npc copy or npc copier the sentry will copy after 2 min i change his location and when i restart the server he respawn back to his original copy location so i cant move him unless when i kill him twice in his new location so that he can save his current position

**Comment by jrbudda** [comment]
Whe you copy a sentry it copies the spawn location also. Are you setting a new spawn point (with /sentry spawn) ?

**Comment by White-Arrow** [comment]
no it stays where the original one is , and also there's another problem . the guards are attacking randomly like some of them attack me and wont attack anyone else and some are not attacking anyone at all unless i kill them and respawn them again ..

**Comment by White-Arrow** [comment]
sorry i forgot to answer u yes i tp them to the new location everytime like 3 times so they will stay there otherwise they will respawn at the original one .. i have to kill each one of them 2 or 3 times so he can remember the new position .. because when i type /spawn to set the new spawn it says use tphere insted because the NPC already spawining somewhere else .. and also attacking random targets problem

**Comment by jrbudda** [comment]
no not /spawn. "/sentry spawn", are you using that? Sentries have their own rememberd spawn location apart from where they are standing and you have to set it.

**Comment by White-Arrow** [comment]
im using /npc spawan .. ok i'll chack that can u help me with the other problem ? im tyring with different accounts to see who are they attacking it's totally random

**Comment by White-Arrow** [comment]
i tried to use /sentry spawn it worked good now but the problem with randomly attacking and not attacking players is till there all versions are updated and i even tried with another server with no other plugins .. it didnt work he's still attacking randomly

**Comment by jrbudda** [comment]
There is an issue I am working on involving a problem with player-type Sentries and line-of-sight. I hope to have a fix out soon. That is probably your issue.

**Comment by White-Arrow** [comment]
well it's kinda a big bug because whenever i change his weapon he stops attacking the problem is happening mostly when he's equipped with a bow i change his weapon with either /npc equip or /sentry equip .. reload the server he attacks .. player leaves his range he stops player returns to range nothing happens .. when player hits him he start attacking again so it's quite a lot of bugs .. thank you for helping .. good luck with solving it

**Comment by jrbudda** [comment]
try it with the very latest Citizens2
http://ci.citizensnpcs.com/job/Citizens2/

**Comment by White-Arrow** [comment]
i have the same version of citizens

**Comment by mcmonkey4eva** [comment]
@White-Arrow - the Citizens download at http://ci.citizensnpcs.co/job/Citizens2/ is a dev build... the version number isn't bumped but it _is_ a newer version.
Also, part of the problem was recently fixed in the latest Citizens and Craftbukkit builds.
