### ISSUE TITLE
Sentry - 40 Second Delay Before Attacking When Given a Target

### ISSUE THREAD

**Issue by mythan** [jrbudda/Sentry#161]
There is a long pause before the Sentry starts attacking it's target after the command is issued. I've got a script where another NPC spawns a bunch of minions (Sentries) but instead they stand there staring blindly into the distance for 30-40s before they start attacking their target.

Do you know what is causing this or how I can work around it?

14:19:58 [INFO] mythanical issued server command: /npc create jimmy
14:20:01 [INFO] mythanical issued server command: /trait sentry
14:20:01 [INFO] jimmy onAttach
14:20:01 [INFO] jimmy onSpawn
14:20:01 [INFO] jimmy onSpawn call load
14:20:01 [INFO] jimmy Load
14:20:05 [INFO] mythanical issued server command: /sentry target add player:myth
anical
14:20:05 [INFO] jimmy- Set Target Null
14:20:44 [INFO] jimmy- Set Target melee
14:20:47 [INFO] jimmy- Set Target melee
14:20:50 [INFO] jimmy- Set Target melee
14:20:53 [INFO] jimmy- Set Target melee
14:20:54 [INFO] mythanical issued server command: /npc rem
14:20:54 [INFO] +> [dNPCRegistry] Deconstructing Denizen NPC jimmy/818
14:20:54 [INFO] jimmy onRemove
14:20:54 [INFO] +> [dNPC] Uh oh! Denizen has encountered a NPE while
                   trying to fetch a NPC. Has this NPC been removed?

**Comment by jrbudda** [comment]
Can't reproduce. Create new ticket if still an issue.
