### ISSUE TITLE
Target vanilla teams

### ISSUE THREAD

**Issue by Souil59** [jrbudda/Sentry#164]
Can you add a target which use minecraft vanilla's teams?

Thanks

**Comment by XxCoolGamesxX** [comment]
Could you please explain what you mean by 'minecraft vanilla team'?

**Comment by mcmonkey4eva** [comment]
@XxCoolGamesxX - http://www.minecraftwiki.net/wiki/Scoreboard#Teams

**Comment by jrbudda** [comment]
Adding.
