### ISSUE TITLE
Jar not recognized

### ISSUE THREAD

**Issue by CodexofWisdom** [jrbudda/Sentry#166]
I have installed the core Citizens 2.0.9 plugin on Bukkit 1.6 with no problems and it works perfectly. However, I put the Sentry.jar in my plugins folder and absolutely nothing happens. It acts as if there isn't a jar there, and doesn't create the folder or config.

**Comment by XxCoolGamesxX** [comment]
One download the last dev of http://ci.citizensnpcs.co/job/Citizens2/changes and download the last of 1.5.2 again http://wiki.citizensnpcs.co/Sentry and be sure you update your craftbukkit to last update.
