### ISSUE TITLE
Brawler

### ISSUE THREAD

**Issue by Robsando** [jrbudda/Sentry#17]
My brawlers only staring at monsters and don't want to do anything, even hit a monster when it is almost on the same block. My archer and stormcaller work fine.

**Comment by jrbudda** [comment]
Cannot reproduce. Make sure you have the latest versions of Sentry and Citizens 2, that your npc has the sentry trait, and that targets are configured properly.

**Comment by Robsando** [comment]
I fix it. Thanks for help. Last time when I update citizens, I placed new file to my plugins directory but not delete older version and I had "Citizens" and "citizens-2.0.1".
