### ISSUE TITLE
I cant type /truit sentry <- Pleas help me

### ISSUE THREAD

**Issue by kraz1234** [jrbudda/Sentry#170]
I really need help always when i selected a guard and typed /truit sentry 
It give me a error to check console

What do i have to do
I made a video about the error check it out pleas
http://www.youtube.com/watch?v=5Se6-aJiGX8&feature=youtu.be
Pleas help me :(

**Comment by XxCoolGamesxX** [comment]
You not have the last update of the plugin you use old one only work for 1.6.2. so go to http://wiki.citizensnpcs.co/Sentry download the last update is 1.5.3 is with work on a 1.6.4.
