### ISSUE TITLE
Sentry error with authme reloaded

### ISSUE THREAD

**Issue by B3stcraft** [jrbudda/Sentry#171]
Hi, when plugin "authme reloaded" is enabled, sentry npcs are not targetable and sentry bodyguards can't take damage or make it!

It doesn't spam anything in console, but I have eliminated all my plugins 1 by 1 , and authme it's the guilty.

**Comment by mcmonkey4eva** [comment]
@B3stcraft 
"AuthMe prevents people, which aren't logged in, from doing stuff like placing blocks, moving, typing commands or seeing the inventory of the current player."

I'd say AuthMe assumes the NPCs are full players and is refusing to let them do stuff until they authorize.

You'll need to...
A: Bug the AuthMe developers about adding support for Citizens2.
B: Replace AuthMe with a compatible plugin
C: Cause your NPC's to authorize themselves... which can be done with a little skill and the Cit plugin Denizen: https://github.com/aufdemrand/Denizen

**Comment by B3stcraft** [comment]
I have posted a ticket in authme, and they think than citicens have changed their api, I dont know what answer to that.

**Comment by mcmonkey4eva** [comment]
@B3stcraft - Tell them to update their Citizen link then ...
