### ISSUE TITLE
Mounted Sentrys lose their strength / lag problem

### ISSUE THREAD

**Issue by GomaTerzu** [jrbudda/Sentry#172]
Hey jrbudda,

i just found out that sentrys who get a mount via /sentry mount are using the default strength again instead of the strength I set.

I created an NPC, made it a sentry, have it 100 strength just for testing, it killed everything one-hit
Then i mounted it and it only dealed the normal amount of damage ´his diamond sword normally does.

Also second problem: Mounted sentry who fight against several enemies cause a rapid decrease of TPS. Horses are probably the main problem with this.

**Comment by XeonG** [comment]
I can confirm.. they also seem to lose strength if you set them to /sentry guard <player>

**Comment by jrbudda** [comment]
Fixed.
