### ISSUE TITLE
error When creating Sentry

### ISSUE THREAD

**Issue by x00dis** [jrbudda/Sentry#174]
I recieve a error when attempting to create a new sentry.  The error states 
"Please report this error: java.lang.NoClassDefFoundError: net/minecraft/server/v1_6_R3/Packet

The server console has 
23.10 09:10:47 [Server] SEVERE at net.minecraft.server.v1_6_R2.MinecraftServer.s(MinecraftServer.java:486)
23.10 09:10:47 [Server] SEVERE at net.minecraft.server.v1_6_R2.DedicatedServer.t(DedicatedServer.java:226)
23.10 09:10:47 [Server] SEVERE at net.minecraft.server.v1_6_R2.MinecraftServer.t(MinecraftServer.java:590)
23.10 09:10:47 [Server] SEVERE at net.minecraft.server.v1_6_R2.DedicatedServerConnection.b(SourceFile:30)
23.10 09:10:47 [Server] SEVERE at net.minecraft.server.v1_6_R2.ServerConnection.b(SourceFile:37)
23.10 09:10:47 [Server] SEVERE at net.minecraft.server.v1_6_R2.PlayerConnection.e(PlayerConnection.java:116)
23.10 09:10:47 [Server] SEVERE at net.minecraft.server.v1_6_R2.NetworkManager.b(NetworkManager.java:296)
23.10 09:10:47 [Server] SEVERE at net.minecraft.server.v1_6_R2.Packet3Chat.handle(SourceFile:49)
23.10 09:10:47 [Server] SEVERE at net.minecraft.server.v1_6_R2.PlayerConnection.a(PlayerConnection.java:829)
23.10 09:10:47 [Server] SEVERE at net.minecraft.server.v1_6_R2.PlayerConnection.chat(PlayerConnection.java:872)
23.10 09:10:47 [Server] SEVERE at net.minecraft.server.v1_6_R2.PlayerConnection.handleCommand(PlayerConnection.java:954)
23.10 09:10:47 [Server] SEVERE at org.bukkit.craftbukkit.v1_6_R2.CraftServer.dispatchCommand(CraftServer.java:523)
23.10 09:10:47 [Server] SEVERE at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:192)
23.10 09:10:47 [Server] SEVERE at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
23.10 09:10:47 [Server] SEVERE at net.citizensnpcs.Citizens.onCommand(Citizens.java:214)
23.10 09:10:47 [Server] SEVERE at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:177)
23.10 09:10:47 [Server] SEVERE at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
23.10 09:10:47 [Server] SEVERE at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:153)
23.10 09:10:47 [Server] SEVERE at java.lang.reflect.Method.invoke(Method.java:601)
23.10 09:10:47 [Server] SEVERE at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23.10 09:10:47 [Server] SEVERE at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
23.10 09:10:47 [Server] SEVERE at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23.10 09:10:47 [Server] SEVERE at net.citizensnpcs.commands.TraitCommands.toggle(TraitCommands.java:152)
23.10 09:10:47 [Server] SEVERE at net.citizensnpcs.commands.TraitCommands.addTrait(TraitCommands.java:59)
23.10 09:10:47 [Server] SEVERE at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:85)
23.10 09:10:47 [Server] SEVERE at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:106)
23.10 09:10:47 [Server] SEVERE at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:115)
23.10 09:10:47 [Server] SEVERE at net.aufdemrand.sentry.SentryTrait.ensureInst(SentryTrait.java:133)
23.10 09:10:47 [Server] SEVERE java.lang.NoClassDefFoundError: net/minecraft/server/v1_6_R3/Packet

**Comment by mcmonkey4eva** [comment]
@x00dis - Please update to CraftBukkit for Minecraft v1.6.4

If you can't, instead downgrade to Sentry v1.5.2 available here: http://dev.bukkit.org/bukkit-plugins/sentry-citizens2/files/26-sentry-1-5-2/
