### ISSUE TITLE
Error on Sentry spawn

### ISSUE THREAD

**Issue by HammerHedd** [jrbudda/Sentry#176]
When sentries that are posed try to spawn I get the following error:

http://pastebin.com/0Rksz8We

I tried downloading the most current builds of citizens and sentry, but still the error occurs.

**Comment by winterfrost1** [comment]
Are you running Sentry 1.5.4 that was uploaded yesterday?  That fixed this error for me.

**Comment by mcmonkey4eva** [comment]
@HammerHedd -
make sure you're running the latest Sentry from: http://wiki.citizensnpcs.co/Sentry
and latest Citizens from: http://ci.citizensnpcs.co/job/Citizens2/
