### ISSUE TITLE
Sentry pushed into void...

### ISSUE THREAD

**Issue by XeonG** [jrbudda/Sentry#177]
Doesn't just respawn.. its annoying having to tp them back.

**Comment by mcmonkey4eva** [comment]
... don't open holes to the void?

**Comment by XeonG** [comment]
you never seen skyblock, emptyworld generators etc why not just fix the problem

**Comment by jrbudda** [comment]
This should be properly fixed in Citizens. It's an easy fix and I will work with them to get it done.
