### ISSUE TITLE
Bug Important : When Sentry Kill something

### ISSUE THREAD

**Issue by ghost** [jrbudda/Sentry#18]
Hi, I install just Vault ,sentry and citizens 2.0.1, but when a guard kill some monster or player, the serveur just FREEZ. I need restart it... Please fix this bug Quickly please...
I try with essential, groupmanager etc, bug thath bug every time...

My save in citizens file :

  '0:
    name: Snuggletummy
    navigator:
      speed: '1.0'
      pathfindingrange: '10.0'
      stationaryticks: -1
      speedmodifier: '1.0'
      avoidwater: false
    traits:
      spawned: true
      waypoints:
        linear: {}
        provider: linear
      equipment:
        hand:
          id: BOW
          amount: 1
          data: 0
          mdata: 0
          enchantments:
            '48': 2
      owner: hijack_hornet
      location:
        world: Avencraft
        x: '-506.50005040906746'
        y: '64.0'
        z: '-1187.123544568326'
        yaw: '900.0036010742188'
        pitch: '-2.6160666942596436'
      sentry:
        toggled: true
        Retaliate: true
        Invincinble: false
        DropInventory: false
        CriticalHits: true
        Targets:
        - ENTITY:MONSTER
        Ignores: []
        Spawn:
          x: '-500.31641017008684'
          y: '64.0'
          z: '-1185.9688117084954'
          world: Avencraft
          yaw: '272.99884033203125'
          pitch: '12.900138854980469'
        Health: 20
        Range: 10
        RespawnDelay: 10
        Speed: '1.0'
        Weight: '1.0'
        HealRate: '0.0'
        Armor: 0
        Strength: 1
        WarningRange: 0
        AttackRate: '2.0'
        FriendlyFire: false
        NightVision: 16
        GuardTarget: Hijack_Hornet
        Warning: '§c<NPC> says: Halt! Come no further!'
        Greeting: '§a<NPC> says: Welcome, <PLAYER>!'

**Comment by jrbudda** [comment]
I Cannot reproduce your problem. What other plugins are you running?

**Comment by ghost** [comment]
Many... But i test runing JUST vault, citizens 2.0.1 and sentry.
If you want, i can send a vidéo of the problem.

**Comment by ghost** [comment]
In fact i have a verygames server with the last recomended build of CB. So, i install all corectly and the server just stop when a sentry kill someone or a monster. So i delete all plugin ecepte this 3 plugins and the problem don't change.

**Comment by jrbudda** [comment]
Are there errors in the console? are you running the latest dev builds of Citizens and Sentry?

**Comment by ghost** [comment]
Yes of course ...

**Comment by ghost** [comment]
you want the errors of the console ?

**Comment by ghost** [comment]
I install all today, so i have the good update

**Comment by jrbudda** [comment]
what build numbers did you install? and are there any console errors?

**Comment by ghost** [comment]
Yes many console error.. Wait it search

**Comment by ghost** [comment]
> 17:53:09 [INFO] [Citizens] Enabling Citizens v2.0.1
> 17:53:09 [INFO] [Citizens] Save method set to YamlStorage {file=plugins/Citizens/saves.yml}.
> 17:53:09 [INFO] [Citizens] v2.0.1 enabled.
> Sentry is in 0.9.5 :
> 17:51:20 [INFO] [Sentry] Enabling Sentry v0.9.5
> 17:51:20 [INFO] [Sentry] Could not register with Denizen
> 17:51:20 [INFO] [Sentry] Could not register with Towny. the TOWN target will not function.
> 17:51:20 [INFO] [Sentry] Could not register with Factions. the FACTION target will not function.

Here, all is ok.
But when a sentry kill something :

> 17:52:15 [SEVERE] java.lang.AbstractMethodError: net.aufdemrand.sentry.GiveUpStuckAction.run(Lnet/citizensnpcs/api/npc/NPC;Lnet/citizensnpcs/api/ai/Navigator;)V
> 17:52:15 [SEVERE] at net.citizensnpcs.npc.ai.CitizensNavigator.stopNavigating(CitizensNavigator.java:145)
> 17:52:15 [SEVERE] at net.citizensnpcs.npc.ai.CitizensNavigator.updateStationaryStatus(CitizensNavigator.java:183)
> 17:52:15 [SEVERE] at net.citizensnpcs.npc.ai.CitizensNavigator.update(CitizensNavigator.java:160)
> 17:52:15 [SEVERE] at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:163)
> 17:52:15 [SEVERE] at net.citizensnpcs.npc.entity.CitizensHumanNPC.update(CitizensHumanNPC.java:138)
> 17:52:15 [SEVERE] at net.citizensnpcs.npc.entity.EntityHumanNPC.h_(EntityHumanNPC.java:85)
> 17:52:15 [SEVERE] at net.minecraft.server.World.entityJoinedWorld(World.java:1245)
> 17:52:15 [SEVERE] at net.minecraft.server.WorldServer.entityJoinedWorld(WorldServer.java:511)
> 17:52:15 [SEVERE] at net.minecraft.server.World.playerJoinedWorld(World.java:1227)
> 17:52:15 [SEVERE] at net.minecraft.server.World.tickEntities(World.java:1125)
> 17:52:15 [SEVERE] at net.minecraft.server.WorldServer.tickEntities(WorldServer.java:428)
> 17:52:15 [SEVERE] at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:564)
> 17:52:15 [SEVERE] at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
> 17:52:15 [SEVERE] at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
> 17:52:15 [SEVERE] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
> 17:52:15 [SEVERE] at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
> 17:52:15 [SEVERE] Encountered an unexpected exception AbstractMethodError
> java.lang.AbstractMethodError: net.aufdemrand.sentry.GiveUpStuckAction.run(Lnet/citizensnpcs/api/npc/NPC;Lnet/citizensnpcs/api/ai/Navigator;)V
> at net.citizensnpcs.npc.ai.CitizensNavigator.stopNavigating(CitizensNavigator.java:145)
> at net.citizensnpcs.npc.ai.CitizensNavigator.updateStationaryStatus(CitizensNavigator.java:183)
> at net.citizensnpcs.npc.ai.CitizensNavigator.update(CitizensNavigator.java:160)
> at net.citizensnpcs.npc.CitizensNPC.update(CitizensNPC.java:163)
> at net.citizensnpcs.npc.entity.CitizensHumanNPC.update(CitizensHumanNPC.java:138)
> at net.citizensnpcs.npc.entity.EntityHumanNPC.h_(EntityHumanNPC.java:85)
> at net.minecraft.server.World.entityJoinedWorld(World.java:1245)
> at net.minecraft.server.WorldServer.entityJoinedWorld(WorldServer.java:511)
> at net.minecraft.server.World.playerJoinedWorld(World.java:1227)
> at net.minecraft.server.World.tickEntities(World.java:1125)
> at net.minecraft.server.WorldServer.tickEntities(WorldServer.java:428)
> at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:564)
> at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
> at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
> at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
> at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
> 17:52:15 [SEVERE] This crash report has been saved to: /home/games/minecraft/openmod/./crash-reports/crash-2012-09-08_17.52.15-server.txt

**Comment by jrbudda** [comment]
Your citizens2 is not up to date. you need build 334+ for the latest versions of Sentry.

**Comment by ghost** [comment]
can you give me a link please ?

**Comment by ghost** [comment]
Here :
http://dev.bukkit.org/server-mods/citizens/

i take the last version... She have just 2day...

**Comment by ghost** [comment]
So you don't need the crash report ?..

**Comment by jrbudda** [comment]
http://wiki.citizensnpcs.com/Sentry
Click the Citizens build 334 link at the top of the page

**Comment by ghost** [comment]
Thanks !
So many hours i loose for just that ^^

You're work is really great ^^ I am french and you're plugin is one of my favorite.
But i have an other question

**Comment by ghost** [comment]
Sentry can swim in water ?

**Comment by jrbudda** [comment]
No, water interferes with pathfinding.

**Comment by ghost** [comment]
ah.. and if a npc fall in water. what we need to do ?

**Comment by ghost** [comment]
kill it ?

**Comment by jrbudda** [comment]
Sentries should teleport out, if they have waypoints.

**Comment by ghost** [comment]
Ok, thx for all. I need to go.
how did you set waypoint ?

And if you have no idea for the next update, make npc who can move automaticly in all direction like a villager ;)

**Comment by jrbudda** [comment]
you can use Denizen to make npc's Wander

**Comment by ghost** [comment]
ok thx ! I have not understand the last comment because my english lvl is a litlle bit... bad.

**Comment by ghost** [comment]
Ciao
