### ISSUE TITLE
Massive Error

### ISSUE THREAD

**Issue by eglbogle** [jrbudda/Sentry#180]
3:54:30 PM CONSOLE: [SEVERE] java.lang.NoSuchMethodError: net.citizensnpcs.api.npc.NPC.getEntity()Lorg/bukkit/entity/Entity;
3:54:30 PM CONSOLE: [SEVERE] at net.aufdemrand.sentry.SentryInstance.initialize(SentryInstance.java:956)
3:54:30 PM CONSOLE: [SEVERE] at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:130)
3:54:30 PM CONSOLE: [SEVERE] at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:108)
3:54:30 PM CONSOLE: [SEVERE] at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:87)
3:54:30 PM CONSOLE: [SEVERE] at net.citizensnpcs.commands.TraitCommands.addTrait(TraitCommands.java:59)
3:54:30 PM CONSOLE: [SEVERE] at net.citizensnpcs.commands.TraitCommands.toggle(TraitCommands.java:152)
3:54:30 PM CONSOLE: [SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
3:54:30 PM CONSOLE: [SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
3:54:30 PM CONSOLE: [SEVERE] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
3:54:30 PM CONSOLE: [SEVERE] at java.lang.reflect.Method.invoke(Unknown Source)
3:54:30 PM CONSOLE: [SEVERE] at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:153)
3:54:30 PM CONSOLE: [SEVERE] at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
3:54:30 PM CONSOLE: [SEVERE] at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:177)
3:54:30 PM CONSOLE: [SEVERE] at net.citizensnpcs.Citizens.onCommand(Citizens.java:214)
3:54:30 PM CONSOLE: [SEVERE] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
3:54:30 PM CONSOLE: [SEVERE] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:192)
3:54:30 PM CONSOLE: [SEVERE] at org.bukkit.craftbukkit.v1_6_R3.CraftServer.dispatchCommand(CraftServer.java:528)
3:54:30 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.PlayerConnection.handleCommand(PlayerConnection.java:968)
3:54:30 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.PlayerConnection.chat(PlayerConnection.java:886)
3:54:30 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.PlayerConnection.a(PlayerConnection.java:837)
3:54:30 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.Packet3Chat.handle(SourceFile:49)
3:54:30 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.NetworkManager.b(NetworkManager.java:296)
3:54:30 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.PlayerConnection.e(PlayerConnection.java:116)
3:54:30 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.ServerConnection.b(SourceFile:37)
3:54:30 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.DedicatedServerConnection.b(SourceFile:30)
3:54:30 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.MinecraftServer.t(MinecraftServer.java:592)
3:54:30 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.DedicatedServer.t(DedicatedServer.java:227)
3:54:30 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.MinecraftServer.s(MinecraftServer.java:488)
3:54:30 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.MinecraftServer.run(MinecraftServer.java:421)
3:54:30 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.ThreadServerApplication.run(SourceFile:583)

**Comment by mcmonkey4eva** [comment]
@eglbogle - update to a more recent Citizens2 build... this one perhaps: http://ci.citizensnpcs.co/job/Citizens2/1021/
(I believe that's the final 1.6.4 build)

**Comment by eglbogle** [comment]
Still the same problem. It worked once, though. Does me creating other Citizens have anything to do with it?

**Comment by eglbogle** [comment]
Here is the new error:
4:57:05 PM CONSOLE: [SEVERE] java.lang.NoSuchMethodError: net.citizensnpcs.api.npc.NPC.getEntity()Lorg/bukkit/entity/Entity;
4:57:05 PM CONSOLE: [SEVERE] at net.aufdemrand.sentry.SentryInstance.initialize(SentryInstance.java:956)
4:57:05 PM CONSOLE: [SEVERE] at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:130)
4:57:05 PM CONSOLE: [SEVERE] at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:108)
4:57:05 PM CONSOLE: [SEVERE] at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:362)
4:57:05 PM CONSOLE: [SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
4:57:05 PM CONSOLE: [SEVERE] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
4:57:05 PM CONSOLE: [SEVERE] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
4:57:05 PM CONSOLE: [SEVERE] at java.lang.reflect.Method.invoke(Unknown Source)
4:57:05 PM CONSOLE: [SEVERE] at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:153)
4:57:05 PM CONSOLE: [SEVERE] at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
4:57:05 PM CONSOLE: [SEVERE] at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:177)
4:57:05 PM CONSOLE: [SEVERE] at net.citizensnpcs.Citizens.onCommand(Citizens.java:214)
4:57:05 PM CONSOLE: [SEVERE] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
4:57:05 PM CONSOLE: [SEVERE] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:192)
4:57:05 PM CONSOLE: [SEVERE] at org.bukkit.craftbukkit.v1_6_R3.CraftServer.dispatchCommand(CraftServer.java:528)
4:57:05 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.PlayerConnection.handleCommand(PlayerConnection.java:968)
4:57:05 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.PlayerConnection.chat(PlayerConnection.java:886)
4:57:05 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.PlayerConnection.a(PlayerConnection.java:837)
4:57:05 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.Packet3Chat.handle(SourceFile:49)
4:57:05 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.NetworkManager.b(NetworkManager.java:296)
4:57:05 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.PlayerConnection.e(PlayerConnection.java:116)
4:57:05 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.ServerConnection.b(SourceFile:37)
4:57:05 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.DedicatedServerConnection.b(SourceFile:30)
4:57:05 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.MinecraftServer.t(MinecraftServer.java:592)
4:57:05 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.DedicatedServer.t(DedicatedServer.java:227)
4:57:05 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.MinecraftServer.s(MinecraftServer.java:488)
4:57:05 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.MinecraftServer.run(MinecraftServer.java:421)
4:57:05 PM CONSOLE: [SEVERE] at net.minecraft.server.v1_6_R3.ThreadServerApplication.run(SourceFile:583)

**Comment by eglbogle** [comment]
Hmm, it is working again. Very wierd.

**Comment by eglbogle** [comment]
No, actually it is not working. When it spawns the NPC, it does not say the error message, but it does not add the trait. When you try and add the trait by doing /trait sentry, it says the error message.

**Comment by mcmonkey4eva** [comment]
@eglbogle ... can you check `/citizens version` and tell me what version and build # it gives you?
Also, what version of Sentry?

EDIT: Actually, maybe I got it backwards the first time... I thinnnnkkk if not that, then it's a version of Citizens too new for the version of Sentry you have...
Get Sentry v1.6.1 from http://wiki.citizensnpcs.co/Sentry
(In the previous versions sections, as the latest version is for 1.7)

**Comment by eglbogle** [comment]
Citizens v2.0.10-SNAPSHOT (build 979)
Sentry v1.6.1
Also, my version of citizens apparently does not have the command of /citizens version

**Comment by mcmonkey4eva** [comment]
@eglbogle - my bad, that was supposed to be `/citizens` to output the version.

Either way, you ignored me earlier, I said
`update to a more recent Citizens2 build... this one perhaps: http://ci.citizensnpcs.co/job/Citizens2/1021/`
Please... actually do that this time.
You need build 1021 - http://ci.citizensnpcs.co/job/Citizens2/1021/

**Comment by eglbogle** [comment]
Oh. whoops. Sorry for frustrating you. It worked, though! Thank you so much!
