### ISSUE TITLE
error with Sentry on my bukkiet server  1.7.2 

### ISSUE THREAD

**Issue by zmw1234** [jrbudda/Sentry#182]
I seem to be getting an error every time a i use sentry on my bukkiet server. The error says this copy the link to see http://prntscr.com/2a16ld i check the console and i get a error that looks something like this but keeps going on.  [21:57:57] [Server thread/WARN]: java.lang.NoClassDefFoundError:. please help me with this i dont know why this happens

**Comment by mcmonkey4eva** [comment]
@zmw1234 - update Sentry - http://wiki.citizensnpcs.co/Sentry
