### ISSUE TITLE
BUGs + ISSUES: Fall Damage; Dispenser Damage; No Stealth etc.

### ISSUE THREAD

**Issue by TestingMC** [jrbudda/Sentry#187]
Good day!

I made an account just to post this. I have citizens2 version v.2.0.9 build 966. Here are the issues that - forgive the expression - bug the hell out of me:

ISSUES:
1. No Fall Damage
   Simple NPCs and Sentries do not seem to take any fall damage, regardless if the commands /npc gravity or /sentry invincible or /npc vulnerable are active or not. This is very annoying especially concerning the fact that in versions prior to the release of horses npc's did take fall damage.
2. No Dispenser Damage
   Simple NPCs and Sentries do not take any damage from items such as arrows thrown by a dispenser, not even if directly put on the block next to the firing dispenser.
3. The command /npc gravity is poorly documented as I do not see its purpose. I spawned an npc (sentry) somewhere high off the ground let it fall while having gravity enabled: the npc started falling down like a feather, slowly and carefully. Same experiment with gravity disabled: the npc fell down normally, like a player would. (taking no damage of course, see 1). Also the /npc pose command could benefit from a lot more documentation and expansion.
4. I do not like how the new (post horse-update) sentries fire at their target even if the target (me for example) is standing behind an obstacle (a tree) completely isolated from the view of the npc. In versions prior to the horse-update the sentry would stop firing completely in the situation stated above and acted as if their target didn't exist. This also was quite irritating but not as irritating as the current situation.
5. Numerous bugs regarding sentries with types such as Wither and Ender Dragon. They just shoot their projectile in a straight direction and don't seem to be moving or doing anything at all, except look good.

IMPROVEMENT SUGGESTION:

I would suggest making the sentries a little less robotic as to the extent of giving a player the possibility of using stealth (sneaking behind their backs + hiding behind obstacles) against them. The way it is now nothing can escape the range of a sentry, not even if the target is well hidden (an archer-sentry for example).

With all this said, I must admire the work of the developers of Citizens2, who made this one of the best plugin of all time! 

Keep up the good work!
Carver

**Comment by jrbudda** [comment]
I think a lot of this has been corrected in newer version. There was a big problem for a while with line-of-sight within bukkit itself. Withers and Ender Dragons are very buggy as NPCs, not a lot can be done there. I will look into the dispensers.

**Comment by TestingMC** [comment]
Thank you for your consideration!
