### ISSUE TITLE
Sentry error with MCPC+

### ISSUE THREAD

**Issue by oblx** [jrbudda/Sentry#188]
Hi, I am using mcpc+ with citizens2 for 1.6.4 and I can't manage to /trait my NPC.

According to citizens developers, the issue comes from Sentry, here is my error : 
http://pastebin.com/rg23YM1B

And the error when the server is booting : 
http://pastebin.com/tY5pz5Jh

Tried with 1.5.2 and 1.8.0 version of sentry.

**Comment by mcmonkey4eva** [comment]
@Cat121 - Please visit the Sentry wiki at: http://wiki.citizensnpcs.co/Sentry and download v1.6.1 from the "Updates" box. (That's the version you need for a 1.6.4 server)

**Comment by oblx** [comment]
This was the right thing to do, thank you and sorry to have asked such a little thing !

**Comment by oblx** [comment]
A small update here, v1.6.1 didn't work for and I had to use v1.5.4 with citizens v2.0.1 mcpc special.
