### ISSUE TITLE
Two Suggestions

### ISSUE THREAD

**Issue by Blamo27** [jrbudda/Sentry#190]
Can you make a command for lying down an NPC's ?
And make a command in order that will interact the NPC's with a craftingtable or other (Chests,etc...) for move the hands of the npc's for more RP (Ex: For a builder).

Sorry for my bad english, it was hard to try to say my suggestions ^^'
And thanks :D

**Comment by mcmonkey4eva** [comment]
@Blamo27 - Sentry is for combat NPCs.
Did you maybe mean to send this to:
Citizens2 (the NPC plugin): http://issues.citizensnpcs.co/secure/Dashboard.jspa
or Denizen (NPC Scripting plugin): https://github.com/aufdemrand/Denizen/issues?state=open

**Comment by Blamo27** [comment]
Yes ^^' thanks !
