### ISSUE TITLE
Cloned sentry

### ISSUE THREAD

**Issue by Mach12** [jrbudda/Sentry#191]
It may be related to some plugin or the amount of lags on my server... but after i kill some guard, it sometimes respawns twice and is seen by the plugin as stuck in dead state.
Moreover, when I ask to remove it (not despawn it) it will remove one but the other one stays, cannot be selected, isn't in the list and respawns if killed, yet still not in the list.

**Comment by mcmonkey4eva** [comment]
@Mach12 - I believe this is an obscure Citizens bug where some NPCs are cloned without explanation. I've seen it a few times myself and heard complaints from some other people. The only currently known fix is a server restart.

If you could find a way to consistently trigger it (enough that anyone could force it to happen), that would be incredibly helpful towards fixing it.
