### ISSUE TITLE
Some Heroes skills do not damage Sentries

### ISSUE THREAD

**Issue by Eliasar** [jrbudda/Sentry#192]
Issue: When casting certain skills from Heroes, Sentries that are vulnerable to normal attacks (axe, sword, bow and arrow, fist) take 0.0 damage. Sentries do not take damage from either direct sources (no in-game item associated), lightning skills, or snowballs (icebolt and firebolt).

Plugins: Spigot, Citizens2, Sentry, Heroes, Vault

Spigot version: 1.7.2-R0.2, build 1204
Citizens2 version: 
Sentry version: 1.8
Heroes version: 1.5.5.1
Vault version: 1.2.29-b370

Steps to reproduce:
- Create npc (/npc create Jack --trait Sentry)
- Turn npc vulnerability off
- Turn sentry invincibility off
- Use /skill icebolt

Sentry returns the following message (picture shown using firebolt, bolt, and flamearrow, which is a skill to enchant bows with flame) 
![Heroes-Sentry-Damage-Issues](https://f.cloud.github.com/assets/200301/1964700/cf52d13a-82b0-11e3-9d94-62cc99d8b6fc.png)

**Comment by jrbudda** [comment]
Damage in minecraft is based on events, when you hit someone with, say, a snowball, there is an event, each plugin gets passed this event in turn. Heroes sees it and applies the correct damage to the thing that was hit. When the event gets to sentry, its still just a snowball, which do 0 damage. So whats going on here is that Heroes isn't applying any damage to the Sentry, and there is no damage for Sentry to apply.

There's nothing I can do from the sentry side to identify a Heroes skill and handle it. Heroes would have to do it.
