### ISSUE TITLE
BUG/ REQUEST: OVERLAPPING NPCs/ 'GROUP' ORGANIZATION

### ISSUE THREAD

**Issue by TestingMC** [jrbudda/Sentry#193]
Issue:

OVERLAPPING NPCs
When setting more than one sentry to guard/ follow you, they end up overlapping eachother. This leads to the sentries shooting themselves instead of their target (if they have bows) and it gets very annoying.

Suggestion:

GOUP ORGANIZATION
An update which would allow multiple sentries not to overlap ('enter') one another and keep a specific (editable) distance between EACH OTHER (not between sentry and player) when following a player would fix the whole issue. Furthermore, this would allow a player to lead an 'organized' army without the sentries looking like a huge pile of 100 men all crammed in a 2x2 area. 

Please consider the above - if the issue can be fixed on way or another, please inform me as I cannot find any solutions on the internet regarding this matter.

**Comment by jrbudda** [comment]
http://wiki.citizensnpcs.co/Sentry#Stats

What you want is the '/sentry follow #" command. Give each bodyguard a different value, typically archers would be father back, etc. Using sentry to make an 'army' is outside the scope of the plugin.

**Comment by TestingMC** [comment]
@jrbudda 
Thank you for your response. I have thought of giving each sentry a different follow-value and realized that it is not a viable option due to various reasons:
- it is individual (does not apply to groups of sentries), making it very frustrating for use with a group of sentries;
- it doesn't solve the overlapping issue, hence if sentries were to cross paths they would still overlap;
- it does not organize a group of sentries, at best it just puts them in a straight line;
- it is space and effort consuming, hence the fact that one would have to use this command EVERY TIME for EACH sentry if they want to make a group;

I used the word 'army' as a hyperbole, an exaggeration. Obviously you would not be able to use this plugin to spawn thousands of sentries. I am talking about a decent group of sentries (over 10). The system that @mcmonkey suggested sounds promising. Such an adaptation would be very useful even for small groups of sentries.

I understand that such an issue cannot be resolved within days. I also understand the fact that we are talking about an open-source 'program' - so requests cannot exceed a certain level. But please consider reopening this thread as I think the issue addressed here is of high importance and maybe will be taken into account.
