### ISSUE TITLE
Lookout Sentrys don't return to their position

### ISSUE THREAD

**Issue by TerraNetworkOrg** [jrbudda/Sentry#2]
If a Sentry Guard follows an enemie to fight him, he won't return to it's position after the fight until he dies (or server restarts?)

Is it possible to send them back after x seconds without targeting an enemy?

**Comment by jrbudda** [comment]
You have to use /npc path to give the Sentry a position or a path. They will return to it after fighting if pathing allows.

**Comment by TerraNetworkOrg** [comment]
Ok thx! :)
