### ISSUE TITLE
Suggestion: Config values for weapon/armour things

### ISSUE THREAD

**Issue by Fureniku** [jrbudda/Sentry#21]
Hello,

I just had a small suggestion for various things with weapons/armour, as follows:

First would be making armour work. I like the defense buff we can give them, but due to its nature it just can't compare to real armour (With real armour, you can still do SOME damage with fists, just not much...). A config option of "cosmetic_armor" as true or false would be great (false meaning armour works as it does with a player)

Secondly, a similar thing with weaponry for swords and bows.

The third would be configs so we can set what items give those spell buffs. We use Spout and MoreMaterials, so I'd love to be able to just put the ID/Data of, say, a magic wand for the fireball.

A fourth extra thing (not too fussed) would be the ability to configure buffs depending on the type of item by adding to a YAML list. That way we can give damage bonuses to weapons in the config, and our users wont be able to change them. It would give a whole load of freedom to our users, because otherwise they'll all just set guards to do 2000 damage per hit :(

Hope you'll consider these :) I'm usually in the IRC if you want to discuss anything.

**Comment by jrbudda** [comment]
Some of this is possible. To use armor non-cosmetically I would have to calculate the damage reduction manually, letting bukkit do it also applies durability loss to the armor and it will break. I don't forsee that happening.

Setting armor to 1 will still allow some damage from fists if critical hits are on.

A Server-wide config file is coming soon, I like the idea of adjustable items and item:damage mappings.

You can always take away the ability to set stats like strength, and let the ops or scripts make sentries with pre-set values.

**Comment by Fureniku** [comment]
I don't see the durability loss being too much of a bad thing but its your call. Personally I like the idea of my users having to maintain their guards - but from what I've seen, not many other servers let their users make the town guards. Maybe it could have a way of auto-respawning the armour when it is nearly depleted?
As for giving them via scripts, I have that in place at the moment, but it isn't as customizable as I'd like. But, it'd at least work fine if you're doing the config - the weapon and damage is a lot more important than the armour and protection to me.

Glad to hear about the config file though, I'll keep my eyes open for that one.

**Comment by jrbudda** [comment]
What isn't as customizable as you'd like? Best method for dispensing sentries is to make some 'template' sentries and use /npc copy to hand them out.

The problem with the armor thing.. people use healing, and high HP, and a variety of other things that make the armor break before the sentry dies, you could 'regen' it but that's messy and against the grain of how most people use them.

**Comment by Fureniku** [comment]
Well, I want users to pay for and equip armour. It'd be a bit more involved to have to do all that via scripts, and as I said before it wouldn't work quite like real armour.

If you can't/don't want to add armour that is fine, If I never asked I'd never know :P

**Comment by jrbudda** [comment]
Done!
