### ISSUE TITLE
[Question/Feature Request] Players don't drop items upon 'Sentry death'?

### ISSUE THREAD

**Issue by incognitojam** [jrbudda/Sentry#213]
Hello,

I would like to know if this is a feature in Sentry, or if it could be added in the future:

"How can I make it so that if a player is killed by a Sentry, they do not drop their items?"

That's pretty much it I guess. If you need any more info, feel free to ask.

Thanks!

**Comment by mcmonkey4eva** [comment]
There is a config option for that.
