### ISSUE TITLE
--type 'monsters' move very slow

### ISSUE THREAD

**Issue by Beefaloaf** [jrbudda/Sentry#22]
If i use a regular player model, the walking speed is normal.  As soon as i use a --type Zombie or Skeleton, they move at a snails speed.   Increasing the speed to 2 helps alittle, but it's still slower than normal.

The NPC created monsters WILL walk at full speed prior to applying /trait Sentry.

**Comment by jrbudda** [comment]
Should be fixed in 0.9.7

**Comment by jrbudda** [comment]
I think fixed.
