### ISSUE TITLE
Possible Conflict with Denizen / Sentry?

### ISSUE THREAD

**Issue by smittywits** [jrbudda/Sentry#221]
So, I have checked all of the plugin versions for Citizens, Sentry, and Denizen and they are all on the same CB version, that matches my server version. I do not know why the error is occurring, however I have figured out that if I uninstall Denizen, the error is no longer produced. Essentially what happens is that while Denizen is installed, Sentries drop items. When Denizen is not installed, Sentry works without any problems. I thought it was a problem with Denizen, but the error is created by Sentry. Any help would be appreciated.

Listed below is the error.
http://pastebin.com/22NQKQTt

Thanks in advance,
smittywits

**Comment by mcmonkey4eva** [comment]
Yeah, you have an outdated Denizen, Sentry is built for a newer Denizen version. You can update to the latest 1.7.9 build of Denizen via http://wiki.citizensnpcs.co/Versions
specifically this build: http://ci.citizensnpcs.co/job/Denizen/1483/

**Comment by smittywits** [comment]
My Craftbukkit Version is 1.7.9-R0.1-10-.. (API Version 1.7.9-R0.2).
My Citizens2 Version is 2.0.3-SNAPSHOT (build 1130) for CB 1.7.9-R0.1.
My Sentry version is 1.8.2. for CB 1.7.9-R0.1.

Denizen Build #1483 (v0.9.4) is the version that was used when I received the error that I listed above. Denizen Build #1525 (v0.9.5) tells me "This Denizen version is not compatible with this CraftBukkit version! Deactivating Denizen!". 

I made sure to check and double check the version compatibilities before I posted a ticket. That's why I'm stuck, because everything should be working properly. What else could there be going wrong?

**Comment by mcmonkey4eva** [comment]
Hm... get Sentry 1.8.2b2 from http://wiki.citizensnpcs.co/Sentry#Updates maybe

**Comment by smittywits** [comment]
I will try that now and post an update as soon as it's done.

**Comment by smittywits** [comment]
It gave me the same issue as the previous build for Sentry did.

However! Moving back to Denizen v0.9.4 and using the Sentry version 1.8.2b2 caused Denizen to load properly. Everything seems to be working both from the back end and in game. I will post an update if I find any other issues.

**Comment by mcmonkey4eva** [comment]
`Moving back to Denizen v0.9.4` you were... supposed to be on 0.9.4... 0.o, if everything's working right now, please close the issue. You can create a new issue if you find a new/unrelated problem. (You can also reopen the issue in the future)

**Comment by smittywits** [comment]
That's the funny part. From what I could tell, it was Denizen that was the wrong version, not Sentry. Sentry was not giving any errors, until the sentries dropped items. Denizen would fail to load any other version than v0.9.4, but Sentry was working properly with everything else and was installed first. Thanks for the help.
