### ISSUE TITLE
Error of Sentry. CLICK ME

### ISSUE THREAD

**Issue by AnonyBart** [jrbudda/Sentry#223]
This is the error from the console when i do "/npc create Town Guard --trait sentry"

4:05:29 PM CONSOLE: WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R3/World
4:05:29 PM CONSOLE: WARN]: at net.aufdemrand.sentry.SentryTrait.ensureInst(SentryTrait.java:134)
4:05:29 PM CONSOLE: WARN]: at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:116)
4:05:29 PM CONSOLE: WARN]: at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:111)
4:05:29 PM CONSOLE: WARN]: at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:376)
4:05:29 PM CONSOLE: WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
4:05:29 PM CONSOLE: WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
4:05:29 PM CONSOLE: WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
4:05:29 PM CONSOLE: WARN]: at java.lang.reflect.Method.invoke(Method.java:606)
4:05:29 PM CONSOLE: WARN]: at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:154)
4:05:29 PM CONSOLE: WARN]: at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
4:05:29 PM CONSOLE: WARN]: at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:178)
4:05:29 PM CONSOLE: WARN]: at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
4:05:29 PM CONSOLE: WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
4:05:29 PM CONSOLE: WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
4:05:29 PM CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767)
4:05:29 PM CONSOLE: WARN]: at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1043)
4:05:29 PM CONSOLE: WARN]: at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:880)
4:05:29 PM CONSOLE: WARN]: at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28)
4:05:29 PM CONSOLE: WARN]: at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65)
4:05:29 PM CONSOLE: WARN]: at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186)
4:05:29 PM CONSOLE: WARN]: at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81)
4:05:29 PM CONSOLE: WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734)
4:05:29 PM CONSOLE: WARN]: at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
4:05:29 PM CONSOLE: WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
4:05:29 PM CONSOLE: WARN]: at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
4:05:29 PM CONSOLE: WARN]: at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
4:05:29 PM CONSOLE: WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R3.World
4:05:29 PM CONSOLE: WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
4:05:29 PM CONSOLE: WARN]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
4:05:29 PM CONSOLE: WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
4:05:29 PM CONSOLE: WARN]: at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
4:05:29 PM CONSOLE: WARN]: ... 26 more

**Comment by mcmonkey4eva** [comment]
You're running a 1.7.9 sentry on a 1.7.10 server. Update: http://wiki.citizensnpcs.co/Sentry#Updates

**Comment by AnonyBart** [comment]
Ok thanks!
