### ISSUE TITLE
Skeletons always firing arrows, despite having melee weapons

### ISSUE THREAD

**Issue by goodbyebluemonday89** [jrbudda/Sentry#225]
As the title states, I have several skeleton npcs with swords/axes/etc equipped. However, they never do melee damage, and always shoot arrows at the player from a stationary point, instead. Is there a way to disable or bypass this?

**Comment by mcmonkey4eva** [comment]
Bypass: recode Sentry, as that's hardcoded https://github.com/jrbudda/Sentry/blob/master/src/net/aufdemrand/sentry/SentryInstance.java#L1625
Sorry :(
dSentry will definitely have better control over things than that.

**Comment by goodbyebluemonday89** [comment]
Ah man. . . That's unfortunate. I guess it's time to ditch sentry permanently. If you'd like help pushing dsentry into working stages, let me know.
