### ISSUE TITLE
Sentry 1.8 Error

### ISSUE THREAD

**Issue by juliaoverflow** [jrbudda/Sentry#239]
It says this when i do /trait sentry java.lang.NoClass.DeFoundError: net/minecraft/server/v1_7_r1/Packet

**Comment by mcmonkey4eva** [comment]
Wrong version of Sentry. http://wiki.citizensnpcs.co/Sentry#Updates

**Comment by MaximumLOL091** [comment]
Please Update Sentry to 1.8.x because I want it now for my server!!!
Please I love this plugin
 for Citizens2
