### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by HollishKid** [jrbudda/Sentry#260]
Hello,

I get the following issue in console;
http://pastebin.com/jgAufVfx

I was simply attacking one of my sentry NPCs, all seemed quite normal to me!
Any ideas on this?

Thanks!

**Comment by mcmonkey4eva** [comment]
Download the latest release off of http://ci.citizensnpcs.co/job/Sentry/

**Comment by HollishKid** [comment]
I downloaded, as suggested, the latest version, I still get the following error spammed in console.

http://pastebin.com/BUWk8M4k

**Comment by mcmonkey4eva** [comment]
A-woops. Looks like Sentry needed a recompile to handle an edit to the CitizensAPI. Build # 35 off the same link should work better.

**Comment by HollishKid** [comment]
No more errors, thanks!
