### ISSUE TITLE
Question for entity move (mob)

### ISSUE THREAD

**Issue by itpao25** [jrbudda/Sentry#263]
Hi, i am trying in these days to create a mob skeleton with target has a specific player, but the mob should remain motionless (should turn only towards the player, watching)
My problem is that the mob **moves** toward the target player.
Can someone help me? 
Ps. I'm using the api
Thanks for the support

**Comment by mcmonkey4eva** [comment]
Why is this in the old Sentry issues page?

There are Citizens utilities to rotate an NPC... use those, and not the navigator.

**Comment by itpao25** [comment]
Thanks for reply
How can i set the target? The mob should lauch arrows toward the target player, this is my question.
For the moment i have spawned a simple player and using a task i spawn the arrows toward the player.

For the rotation i have used a trail LookClose.
If this is not correct page, can you send me the link when i can recreate issue? Thanks

**Comment by mcmonkey4eva** [comment]
https://github.com/CitizensDev/Citizens2/issues is maybe what you want?

**Comment by itpao25** [comment]
Yes, but I was going to use Sentry, I was wondering if there's a way to do this using Sentry

**Comment by mcmonkey4eva** [comment]
We don't even use Sentry anymore, Sentinel is preferred: https://github.com/mcmonkey4eva/Sentinel/blob/master/README.md

**Comment by itpao25** [comment]
Good! Thanks :-)
