### ISSUE TITLE
Owner bug

### ISSUE THREAD

**Issue by Forting477** [jrbudda/Sentry#271]
When I create NPC and give him trait sentry its write "You, or the server, must be the owner of this Sentry to execute commands" but Im op and I created this np
![Screenshot_1](https://user-images.githubusercontent.com/59089514/174652902-f4043330-3f7e-4dee-a4a7-a0b8abdfeea3.png)

**Comment by mcmonkey4eva** [comment]
Sentry stopped being updated many years ago. Use Sentinel: https://www.spigotmc.org/resources/sentinel.22017/

**Comment by Forting477** [comment]
I solved this problem. I installed older version of citizens than I had before

**Comment by sentry266** [comment]
Can u tell me how u solved this owner issue
