### ISSUE TITLE
Sentry Resetting

### ISSUE THREAD

**Issue by nima0041** [jrbudda/Sentry#28]
I make a Sentry with /npc create Guard --trait sentry.
And after I give it a range with /sentry range 30.
Then I do /npc equip, and give it armor.
After that I do /npc path, and make one waypoint, where it is standing.
Then I do /sentry greeting Watch out for the werewolves!
At last I do /sentry target add group:werewolf.
It all works, but after 10 minutes, it says that they aren't sentrys anymore,
and I have to remake them all over again. Any fix?

**Comment by jrbudda** [comment]
Never head of this one. What 'says' they aren't sentries anymore? are you reloading anything? are there console errors?

**Comment by nima0041** [comment]
Just found out they mess up when I reload Sentry. A server restart helped. But now I have another problem. The guards attacks the players, but it doesn't hurt them. The players won't lose any hearts, when the guards attacks them. So it ends up with my players always killing the guards :P

**Comment by jrbudda** [comment]
Check their Strength setting.

**Comment by nima0041** [comment]
Here is my config just so you can see it ^^: http://pastebin.com/162X5Ent

And now I have another problem, after like 12 hours, the Sentrys just disappear.
Only the Sentrys, not the normal Citizen npcs. A server restart will bring the Sentrys
back, do you know the problem? :)
