### ISSUE TITLE
event:pvp

### ISSUE THREAD

**Issue by Beefaloaf** [jrbudda/Sentry#29]
Using event:pvp doesnt seem to have an effect.  We played around with this for almost an hour, and the npc's only attack us one time.

We could fight and they wouldnt move.  When a player died, nothing happened.
The only time we got a result was when i got knocked off a ledge, near an npc.  I didnt die, but the Sentry came after my attacker.

Increased range to 20 with no results.

**Comment by jrbudda** [comment]
By chance are you testing it in a no-pvp zone? Sentry will only respond to a pvp event if it actually causes damage.

**Comment by Beefaloaf** [comment]
I've tried in a WorldEdit region with pvp allowed, and also tried in open area.  Same results.  

If you want, we could set you up with some access on my server so you can test it out yourself.  Or maybe you can login and we can troubleshoot it.

**Comment by jrbudda** [comment]
I've tested it on my end and it works as intended. I would check that the target is applied correctly, doesn't have any 'ignores', and that the sentry has line-of-sight to the players involved.

**Comment by Beefaloaf** [comment]
Im creating a fresh npc, applying /trait sentry.  Then setting /sentry target add event:pvp.
The ignore table is [] empty.

I did just find something interesting though....

If i type /sentry target list, I can see that it has 1 target of EVENT:PVP.
If i type /sentry info, i see Target: Nothing

Everything else looks correct on /sentry info.  (stats)

Closed on accident
