### ISSUE TITLE
event:pvp

### ISSUE THREAD

**Issue by Beefaloaf** [jrbudda/Sentry#31]
I closed this ticket on accident. Setting a sentry target to event:pvp has no effect.

I know you said you were unable to reproduce this problem. Perhaps when you get a chance, you could login and ill give you full perms. That way you could troubleshoot on a working example.

Ive tried setting the region flag to all settings.  

pvp allow
pvp deny
pvp cleared

Im going to disable all other addons to eliminate the possibility of conflicts. Will post results.

**Comment by Beefaloaf** [comment]
Disabled all addons except Citizens and Sentry.  Same results.  
I'm using 
Citizens 2.0.1 dev build #360
and
Sentry 0.9.9 - 2

**Comment by jrbudda** [comment]
If you can, come to our IRC

http://webchat.esper.net/?channels=citizens

**Comment by Beefaloaf** [comment]
Thank you jrbudda.
/sentry info revealed the [vis] was at 0.  Adjusting the nightvision range was the fix.
