### ISSUE TITLE
Major lag event if you tp  a sentry to you whilst your on a ladder

### ISSUE THREAD

**Issue by Craigdb** [jrbudda/Sentry#32]
I don't know how well you can help me as there are no error logs or anything, just as stated. The server becomes completely unresponsive and disconnects clients. It does eventually resume itself. This was tested with a plain NPC and had no event, but it re-occured when an NPC was changed to a sentry whilst on a ladder.

See what you can do with this one.

**Comment by jrbudda** [comment]
I can't reproduce this... to be clear, you are climbing a ladder, you have a normal npc selected and you call /trait sentry (while still on the ladder) and the server freezes?

**Comment by Craigdb** [comment]
Not quite... One of two options tested...
1: Stand on a ladder a tp a sentry to you
2: Get a unassigned Npc to go down a ladder (path) and whilst he's on the ladder assign him to sentry. Either option made the server "freeze" long enough to disconnect everyone... Console totally non-responsive.

**Comment by jrbudda** [comment]
How did you manage to get a npc to path down a ladder? They're not supposed to be able to climb ladders...

**Comment by Craigdb** [comment]
On 20 September 2012 06:55, jrbudda notifications@github.com wrote:

> How did you manage to get a npc to path down a ladder? They're not
> supposed to be able to climb ladders...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jrbudda/Sentry/issues/32#issuecomment-8706530.
> 
> I'd have to ask my Moderator that actually performed that test... I think
> he just had him running off a ledge that happened to have a ladder on the
> side.

Here is what is causing me the main problem... if you are familiar with the
teleporter in 'runecraft', I have a portal room set up in my main town,
which links to everyones homes... it is underground, and at ground level
above it is a inbound portal for people to link in from (a ladder leads
down to the outbound portals). So... what happened is the player set a
sentry to guard him then went home. The sentry stayed waiting for him at my
town... somehowe in the process, when he returns to my town and uses the
ladder the sentry locks in and resumes guard duties and the first think it
does is tp to him... whilst the player was on the ladder... bang... freeze.

It is probably my unique set up with the portal room that has brought this
bug into view.

What might actually work to test it is just make a sentry when at the top
of a large ladder... set him to guard you then proceed down the ladder. I
think he will not follow, then attempts to tp once out of a certain
range... that's when it freezes.

This is the theory as I have witnessed the crashes but it was a colleague
that was using the NPCs at the time.

**Comment by jrbudda** [comment]
Okay, one of the guys in IRC was able to reproduce the freeze, it's something deep in the citizens core. Will have to try and get a workaround going, core may not get worked on for a week or 2.

**Comment by jrbudda** [comment]
Tried putting a workaround in sentry v1.0, needs to be looked at in citizens core as well.

**Comment by Craigdb** [comment]
Thanks... Just loaded 1.0 do we can test it over the weekend

**Comment by Craigdb** [comment]
Just so you know the patch hasn't worked but I understand what your saying about it being in the citizens code. Just thought you should know that, as the functions of vines and waterfalls have simular physics, they create the same result. It is most obvious with the guards as most other NPCs will not try to follow a vertical path or tp to such a location. Have you contacted citizens designers about this or will it be better if I do?

**Comment by jrbudda** [comment]
He patched in a potential fix this morning, I have to do some testing on my end and update sentry maybe. Do you have a reliable set of steps to reproduce the freeze with bodyguard? I was only able to do it using waypoints.

**Comment by Craigdb** [comment]
Easiest way... Set a sentry to guard you then climb a large ladder or water... Long enough to make the Npc tp to you whilst still in climb mode.

**Comment by jrbudda** [comment]
Looks like the change in citizens core is working... I will have to update sentry to fully solve the problem. I think version 0.9.9.2 might be coded in such as way that the fix in c2 would work with it, if you need this solved immediately.

**Comment by Craigdb** [comment]
Just to clarify... If I get the latest cit2 build you recommend dropping sentry 1.0 back to 0.9.9.2?

**Comment by Craigdb** [comment]
Just an update... Tried cit 381 with both 1.0 and 0.9.9.2 and it almost looked like 0.9.9.2 was working.... The 20 block up waterfall scaling still bombed. It seems better though. Thanks for your efforts.

**Comment by Craigdb** [comment]
Just an update to confirm what you have said...
I loaded Cititens2 382 (changes ref our path issues) and you are correct that sentry 0.9.9.2 no longer crashes out the server however sentry 1.0 does. We have distinct progress! Thanks.

**Comment by jrbudda** [comment]
1.0.1 Sentry and Citizens2 382+ should resolve this totally.
