### ISSUE TITLE
Damage Problem :/

### ISSUE THREAD

**Issue by dynozzy** [jrbudda/Sentry#36]
Everytime i hit my npc's its says 
**\* You hit  <NPC> for 200 damage
and then they dies.
I think all mobs does that much damage to because they one hit the NPC's to.
Would really appreciate an explanation.

**Comment by jrbudda** [comment]
You have another plugin that is affecting damage.

**Comment by dynozzy** [comment]
The only thing that could effect the damage on NPC's is Heroes i guess. But I cant find any solution :(
I still think its odd that i dont hit that much on mobs :/

**Comment by jrbudda** [comment]
How do you know you dont do that much damage to mobs? I think with Heros the damage and health of everything is increased. Set the Sentry to have 1000 life or something.

**Comment by dynozzy** [comment]
Well all the weapons does the same damage then :/
