### ISSUE TITLE
Suggestion: Loot table

### ISSUE THREAD

**Issue by Kardocraft** [jrbudda/Sentry#39]
I think a loot table would be very useful for sentry. Instead of always dropping what they wear it would be more fun if you could set a loot table with a certain chance of dropping. 
For example you have a npc bandit wearing a leather helmet and a stone sword. Then you make a loottable: With 10 percent change dropping his leather helmet 
0 percent dropping his sword 
20 percent dropping a iron ignot
5 percent dropping 2 iron igntos.

**Comment by jrbudda** [comment]
I think this would be better left to Denizen and the NPCDeath trigger. That allows much more freedom than a fixed mmo-style loot table.
