### ISSUE TITLE
Add economy-support

### ISSUE THREAD

**Issue by TerraNetworkOrg** [jrbudda/Sentry#4]
Well this could be a longtime-project, but it would be really cool if every command / stat / option of creating a sentry would cost the user an amount of money.

Example:

base-attack-cost: 100

Every point of attack strength would cost the user 100 credits.

/sentry strength 10

would cost him (10x100) 1000 credits.

**Comment by jrbudda** [comment]
This could be accomplished with commandbook or some other aliasing plugin without modifying Sentry.
