### ISSUE TITLE
Sentries becomes Brawler even though its holding a Sword

### ISSUE THREAD

**Issue by born2kill97** [jrbudda/Sentry#41]
I equipped my Sentry with an Iron Sword, and whenever it attacks someone, the sword will disappear and it becomes a brawler.

In the config of sentries, attack types, I have:

 EliteGuard: 267

I even tried:

 EliteGuard: IRON_SWORD

But Sentries will keep becoming a brawler until it respawns, which they will then hold the sword again. 

I'm using latest Citizens and Sentry plugin.

**Comment by jrbudda** [comment]
Are you using Heros by any chance?

**Comment by born2kill97** [comment]
Yeah I am using heroes.

**Comment by jrbudda** [comment]
Does it still do it if you disable heros?

**Comment by born2kill97** [comment]
Give me a minute as I test

**Comment by born2kill97** [comment]
Oh i think i just figured out the problem...

Yeah when I disable heroes, then sentries work correctly.

I think this is due to the default class because the default class cannot hold anything, perhaps if i change it so that the default class can hold all items and tools, then maybe it will work properly.

**Comment by born2kill97** [comment]
Ok My theory works, All the Sentries work well with Heroes now.

Thanks for your help :D

**Comment by jrbudda** [comment]
Great
