### ISSUE TITLE
Sentries won't stop guarding.

### ISSUE THREAD

**Issue by cotjones** [jrbudda/Sentry#44]
If I see this correctly after you use the /sentry Guard <player> command, to get the sentry to stop guarding the player you use the command /sentry guard. This isn't working for me, he just keeps following, You can however change his target he is guarding. You just can't make him stop following people and guard a location instead.

It does say "Sentry is now guarding a location" but when you do /sentry info it still says guarding "Craftplayer{name=<playername>}.

**Comment by jrbudda** [comment]
What version are you using? I believe this was fixed a while ago.

**Comment by cotjones** [comment]
I probably have an outdated version, it's pretty old. I'll download the new one, Thanks!
