### ISSUE TITLE
Suggestion: better movement AI

### ISSUE THREAD

**Issue by hypercross** [jrbudda/Sentry#45]
So currently the archers would stand still when they attack you - even if you are holding a sword and charging towards them. 

I know this is the same behavior as skeletons but it would make a lot more sense for the rangers to keep a distance from their targets. Unless the sentry has the option to swap to his melee weapon.

I assume swapping weapons and walking away can be done with Denizen - but that's a lot of scripting that you have to assign to whichever step you want the sentry to fight. And the proximity trigger don't work on monsters, so the rangers can't change to sword based on that information.

Melee sentries could also use some random movement to the left or right to make them harder to aim. I feel that these behaviors are natural for a player so it could be implemented by default in the Sentry plugin. 

thanks for the great plugin !

**Comment by jrbudda** [comment]
Currently all npc movement is handled by minecraft directly using very basic pathfinding. It's possible in the future if Bukkit provides the functionality to tap into skeleton AI etc. Until then I don't forsee this being added directly to Sentry as AI is very, very complicated.

Switching to a melee weapon is something that could be done now, Its been asked for before. I'll think about it, problem is how to 'equip' and save two weapons, there's no support for that at all at the moment.
