### ISSUE TITLE
Suggestion: No Knockback Option and No Push Option

### ISSUE THREAD

**Issue by born2kill97** [jrbudda/Sentry#47]
This is a suggestion that might be beneficial for some RPG servers:

1.) No Knockback

I have a hard time trying to figure out how to make it so that an Archer will guard an area and will stay at its position, and also move back into that position if it was to be hit by something.

Basically, if I make an Archer with 30 HP, all a player have to do is hit it once, and he will be saved, because the archer can't shoot him anymore, assuming that the archer is guarding a tower.

So maybe have an option where you can disable it Knockback so that archers will be much more useful.

2.) No Push

What I hate the most is that some of my players would purposely push NPCs off of a ledge, and the NPC would then be out of position.

IT would be awesome if you can add a No Push feature on this plugin.

Thanks a lot!
- Bornio

**Comment by jrbudda** [comment]
A single waypoint (/npc path) will make the archer move back into position if moved off it.

**Comment by born2kill97** [comment]
Ok I did what you mention about NPC path. Now the problem is that for some/many NPCs, they dont go back to guarding their spot after being killed.

**Comment by jrbudda** [comment]
They should always go back to their spot, make sure you are using the latest build of citizens 2.0.3, I think its 481

**Comment by 1Mitchel1** [comment]
sup bornio im with u in github from now :)

**Comment by 1Mitchel1** [comment]
jrbudda is right npc should return  to there old spot when killed like for players we have a bed in my friends server it is like that though i do lno the plugin that he has used

**Comment by 1Mitchel1** [comment]
maybe if the archers had a knockback wich would make the npcs stronger wich would give them a skilllevel of a real player instead of a sucky npc noeone can lose to btw destro i think it can u add some coding line to  ad like another line saying something else
