### ISSUE TITLE
0 damage dealt to sentry.

### ISSUE THREAD

**Issue by Saverous** [jrbudda/Sentry#48]
I can't seem to damage my own sentry, i just hit 0 damage.
it says 
XXXX hit 0 damage 

I've got a number of plugins but i don't have PEX installed. 

I've checked the config and turned friendly fire on.

I can give you a list of my plugins if requested but i don't think that my plugins affected it.

**Comment by jrbudda** [comment]
It has to be a plugin, that error is commonly caused by Modifyworld, I haven't seen any other plugins cause that same effect, but it's certainly possible. Try removing or disabling plugins til the problem goes away.

**Comment by Saverous** [comment]
hmmm i don't have Modify world plugin but i'll keep trying

**Comment by Saverous** [comment]
after i while, i got the sentrys to attack each other but they encounter the same problem, they can't be kiled

**Comment by Saverous** [comment]
ok got the problem thanks.

**Comment by jrbudda** [comment]
what was it?

**Comment by Saverous** [comment]
The problem was the plugin: AncientRPG it somehows puts the sentry or citizen as a "player", by removing it, i could damage the Sentry once more. After 4 hours of more testing, if found that customized spells from Ancient RPG that deal damage will still affect sentrys.The only problem is the base attack, hitting it won't damage the sentry, but spells can.

**Comment by Saverous** [comment]
errr sorry for the 7 hr late reply, i wasn't goign to stop until i got the reason.

**Comment by jrbudda** [comment]
I see, well, I'll add it to the known conflicts
