### ISSUE TITLE
Not allowed to edit Sentrys owned by server

### ISSUE THREAD

**Issue by TerraNetworkOrg** [jrbudda/Sentry#5]
Even if i'm OP or have the sentry.\* node i'm not allowed to edit sentrys in ownership of the server, i think this should be possible.

**Comment by jrbudda** [comment]
Next build anyone with the citizens.admin permission will be able to edit server-owned Sentries.

Thanks for the suggestion.

**Comment by TerraNetworkOrg** [comment]
You're the greatest, thx! :)
