### ISSUE TITLE
Sentry's have XRAY Vision

### ISSUE THREAD

**Issue by Erolias** [jrbudda/Sentry#51]
Sentry's currently are seeing through walls makes stealth missions overly difficult.

**Comment by jrbudda** [comment]
I assume this is with bukkit 1.4.2? some changes were made to the line-of-sight code, will investigate

**Comment by jrbudda** [comment]
I can't duplicate this. I placed a sentry on one side of a wall with entity:monster, and a zombie on the other. He does not react to the zombie if he cannot see it.

Maybe try updating your cb and citizens2?

**Comment by Erolias** [comment]
Yes we are in 1.4, and I haven't tested it on entity:monster, I have a
quest mission to go to a position(that is inside of a fort) the fort has
archers, a wizard, and melee npcs in it with night vision level 9, target
entity:player.
befor 1.4 you could sneak in and past them in the dim candle light, now you
get struck by lightning from the wizard when his on the other side of the
wall from you(whenever your in his 12 block detection area

**Comment by jrbudda** [comment]
Try it with the very latest build of citizens2
http://ci.citizensnpcs.com/job/Citizens2/523/
And let me know if it's still a problem.

**Comment by Erolias** [comment]
Nope thank you that fixed it, ty very much, i and the rest of the guys on
our server really enjoy these plugins, so thank you for all the help.

shameless plug to follow....

ecosance.provisionhost.com
port 25565

and thanks again very much
