### ISSUE TITLE
Sentries Error

### ISSUE THREAD

**Issue by itsmethatswho** [jrbudda/Sentry#52]
I just downloaded the new recommended build and I'm getting this error:

http://pastebin.com/Pr1rdjNr

**Comment by jrbudda** [comment]
Update your citizens2.

**Comment by itsmethatswho** [comment]
I have the current recommended build.  I tried the latest dev build and all
traits stopped working.  Which citizens 2 would you recommend?

**Comment by jrbudda** [comment]
i dunno what you mean by recommended build, you should be using the very latest c2 dev build if you are using minecraft 1.4.2

**Comment by itsmethatswho** [comment]
By recommended build I meant I had been using R: 2.0.2 (Build
#370)http://dev.bukkit.org/server-mods/citizens/files/19-2-0-2-build-370/
for
CB 1.3.2-R0.1.  When sentries stopped working though I tried the dev build
544 and now 545.  Citizens2 isn't loading for me with that build though.  I
guess I should take that up with them though :P

**Comment by itsmethatswho** [comment]
erm ya I wasn't using 1.4.2.  Its working with that CB.  Sorry about the
confusion and thanks for the help.
