### ISSUE TITLE
OverLag in the Sentry

### ISSUE THREAD

**Issue by XxCoolGamesxX** [jrbudda/Sentry#54]
I it a test in the server with a plugin name Nolagg for a monitor of the plugins. I see your plugin is 3376.24 ms in 500 ticks. So yup.

Here the info what is lag in the plugin of Sentry:

Here the Photo: https://dl.dropbox.com/u/16158672/bug%20of%20npc.JPG

and the Examination of Nolagg:  https://dl.dropbox.com/u/16158672/2012_11_04-13_55_32.exam

My Citizens is 2.0.4 - 555
My CraftBook is 1.4.2-R0.2 Build #02455.

Best Regards,
Charles Follet

**Comment by jrbudda** [comment]
That does seem like a lot of processing time. Couple questions:
How many Sentries do you have?
What targets and ignores do they have?
What are the Specs of your server PC ?

One thing you can try is in the Sentry config.yml you can increase the LogicTicks setting from 10 to something higher, like 20 or 30. This will slow down the responsiveness of the sentries but use less CPU.

**Comment by XxCoolGamesxX** [comment]
How many Sentries do you have?
I have 13 of the Sentry npcs.

What targets and ignores do they have?
I think is max 2 to 3.

What are the Specs of your server PC ?
We have 2GB of RAM. We do not now what is the CPU specs of your server become is host by http://beastnode.com/

More Info:
Here the save of all the npc of Sentry: https://dl.dropbox.com/u/16158672/saves.yml

But go to test it is not lag i put in 30 in the LogicTicks you say.

**Comment by jrbudda** [comment]
Hmm this is very strange, all of that lag is caused by 1 Sentry. I do not know which one or why... Only 2 of your sentries have targets. Perhaps you can try removing or de-spawning each sentry until the lag goes away?

**Comment by XxCoolGamesxX** [comment]
Ok. Look like it stop to lag it we put in LogicTicks to 30. But i go to test it. To see it go to lag a again...

**Comment by XxCoolGamesxX** [comment]
Look like it stop to lag in the 2.0.4 - 559 of Citizens.

**Comment by XxCoolGamesxX** [comment]
Now is fix the lag. Go to close the issue.
