### ISSUE TITLE
Arrow damage does not trigger sentry retaliation

### ISSUE THREAD

**Issue by psirusa** [jrbudda/Sentry#57]
I have several sentries set up as mini-bosses in my world, they are set to guard particular areas and retaliate if attacked. The issue is that the sentries will not retaliate against ranged damage, so that someone can stand outside of their attack range and fire arrows without the sentry acquiring them as a target.  Is this a feature, or a bug?

**Comment by jrbudda** [comment]
The sentry should retaliate unless it can't find a path to the attacker, are the mini-bosses ranged or melee?

**Comment by TerraNetworkOrg** [comment]
Hi jrbudds i have nánother problem with ranged attacks.
Sentries hitting each other with any kind of ranged weapon will start attacking each other, no matter wich setting i use (tried nearly every combination now)
I even tried to stop ranged damage events when two Sentries with the same name (all my Sentries are called "Stadtwache" (town guardian) but they are still attacking each other :(

**Comment by jrbudda** [comment]
Turn off retaliation.
