### ISSUE TITLE
Massive CPU load with 1.4.4 

### ISSUE THREAD

**Issue by mixxit** [jrbudda/Sentry#60]
my server is dying due to massive cpu load and it looks like it might be sentry after running a visualvm profiler on it

Here's the results! https://dl.dropbox.com/u/25535993/qq.html

Seems to be something running the spawner

Dropped sentry to test and server has been stable for 7 hours now

Can you take a look? Thanks!

**Comment by mixxit** [comment]
was found to be an issue with the unload chunks change to citizens

special version that keeps the chunks alive has been given and has been stable since

**Comment by jrbudda** [comment]
Also fixed from sentry side in 1.2.3
