### ISSUE TITLE
[Sugjestion] /Sentry Target Add/ignore FLAG:name:Integer

### ISSUE THREAD

**Issue by Matterom** [jrbudda/Sentry#64]
Idea behind this is what i thought would be a good work around Instead of More Faction/Towny/LAND GRAB support, But this can be expanded with Jeebis's denizen extension, apply the number allows Say a security status to be easily changed, without altering every guard's target list to include or remove that player.

**Comment by jrbudda** [comment]
Maybe, we'll see what new possibilities open up in denizen .8.
