### ISSUE TITLE
Not working with Bukkit 1.4.5-R0.3 and denizen

### ISSUE THREAD

**Issue by TMAC-Kratos** [jrbudda/Sentry#66]
In you change log it says you updated it to work with 1.4.5-R0.3, but i still get the error that the nms changes give.

Bukkit version: 1.4.5-R0.3 Build # 2527
Citizens version: Build #628
denizen version: Build #609
sentry version: 1.2.4

Error stacktrace:
http://pastebin.com/96KUtsFR

**Comment by jrbudda** [comment]
Sentry is not currently compatible with Denizen 0.8
