### ISSUE TITLE
Renaming NPC removes armor

### ISSUE THREAD

**Issue by NotYetRated** [jrbudda/Sentry#72]
Renaming the NPC removes all armor. Makes it difficult for me on my server to /npc copy pre-configured sentry's.

I have "default" class settings for a ton of different sentry's with default easy to remember names. I would like to be able to /npc copy these template NPC's to paste around towns and such. The armor dropping off on rename is a bit of a pain.

**Comment by jrbudda** [comment]
Does the same thing happen to non-sentry NPCs ?

**Comment by NotYetRated** [comment]
Ya know, I do not actually know. I can check in a bit when I am back at a PC.

Also, I equipped using /npc equip, not sure if that also affects it. 

EDIT:  Normal NPC's do not drop armor when name changing.

**Comment by jrbudda** [comment]
I can't duplicate this, my npcs, sentry or not, don't lose anything with /npc rename. What build of citizens are you using?

**Comment by NotYetRated** [comment]
Ahh is only happening if renamed when the chunk is unloaded. I think it was really connected to the /npc tphere    /npc copy issue I was having, which looks like it is Citizens itself. Apologies!
