### ISSUE TITLE
Buggy Sentry TPHERE

### ISSUE THREAD

**Issue by NotYetRated** [jrbudda/Sentry#73]
I am uncertain if this is Citizens or Sentry, but it only affects me on Sentry trait NPC's.

If I /npc copy a Sentry that is a good distance away (over 100 blocks) it does not really want to actually copy the sentry. I have to continually /npc tphere rapidly followed by a /sentry spawn to get the NPC to actually copy a good distance away.

**Comment by jrbudda** [comment]
what does happen when you do npc copy? and how do you get it to work with npc tphere?

**Comment by NotYetRated** [comment]
Honestly, I am not sure what happens. Here is a step by step.

-Select NPC1
-Teleport myself to say, another town 1000 blocks away.
-Type /NPC copy, It tells me it copied, I can see a duplicate NPC1 in the /npc list, but I do not see the NPC itself
-Using /npc tp, to TP to the npc itself just teleports me to the correct location, but no NPC is there.
-Continually /npc tphere and /sentry spawn  will eventually get the NPC to show properly.

I have tested on a non-Sentry NPC and this does not happen.

EDIT: Could it possibly have to do with copying from an unloaded chunk? I TP and execute the command rather fast, but do not know if the chunk has already unloaded or not. I would not be able to test this for a few hours or possibly not until tomorrow. Not sure if it even matters, just would like to help if I can. :)

**Comment by jrbudda** [comment]
I'm fairly sure its cause the chunk is unloaded. Odd that it only happens to sentries. I will have to look into it.

**Comment by NotYetRated** [comment]
It is entirely possible that coincidentally when I have teleported non-sentry NPCs their chunk was loaded. And when I have copied sentry NPCs their chunk was no longer loaded. My non sentry NPC templates are all near populated areas. My sentry templates are all off to the side, not necessarily populated areas.

I can test soon and let you know.

**Comment by jrbudda** [comment]
I'm having the same problem with non-sentries, so its a problem in citizens. I'll let them know.

**Comment by NotYetRated** [comment]
Ahh, I apologize for posting it to you before investigating myself further. It appears the NPC item dropping is also due to an NPC being renamed while in an unloaded chunk. :)

**Comment by jrbudda** [comment]
Try with build 656 of Citizens2
