### ISSUE TITLE
Server OP's and Admins with * Perms cannot touch other players Sentry's

### ISSUE THREAD

**Issue by NotYetRated** [jrbudda/Sentry#74]
I cannot really do anything with sentrys who belong to other players, even though I am OP. This is true with and without \* permission node. 

It tells me I am not the owner when I select an NPC I do not own and do /sentry info, or other commands. 

Not sure if it is intended or not, but as OP, I kind of require knowledge about each Sentry's stats in case an admin of mine ever goes rogue and edits stats haha. Or anything of the sort.

**Comment by jrbudda** [comment]
Following the pattern that Citizens uses, you can only edit NPCs you own, or NPCs with the owner set to 'server' while having the citizens.admin permission.
