### ISSUE TITLE
[SUGGESTION] Sentry Grouping

### ISSUE THREAD

**Issue by NotYetRated** [jrbudda/Sentry#75]
Allow for Sentry "grouping".

Set multiple Sentry's to the same group, allowing for quick and easy editing of stats.

Example:

I have 10 archer guards in a town, it would be nice to be able to select them as a "group" to edit their stats, instead of going through and editing each one individually.

**Comment by jrbudda** [comment]
There's been some talk of multi-select being added to Citizens. If that happens Sentry will support it, but I won't be adding that functionality to just Sentry.

**Comment by NotYetRated** [comment]
Excellent, thanks for the heads up. :)
