### ISSUE TITLE
Target "NATIONENEMIES" not functioning

### ISSUE THREAD

**Issue by NotYetRated** [jrbudda/Sentry#76]
Have a bunch of Sentries set with "/sentry target add NATIONENEMIES" and the sentry is not auto targeting enemies. if I "/sentry target add NATION:NAMEOFNATION" it will function properly, and target enemies of "NAMEOFNATION".

**Comment by jrbudda** [comment]
Nationenemies doesnt do anything by itself, when it actually adds the target it should say the name of the nation. Maybe it's failing to lookup the nation the sentry is standing in properly. try specifying nationenemies:name

**Comment by NotYetRated** [comment]
NATIONENEMIES:NAME works, is just "NATIONENEMIES" used for other purposes? I had thought to just add it as a generic TARGET tag in my config so they always target enemies of the nation they are in...

**Comment by jrbudda** [comment]
Sentries can't be in a nation, the idea is that if you do 'add nationenemies' its supposed to look up the nation of the block the sentry is standing on and add that as that target. It only does that once, when you add it.

**Comment by NotYetRated** [comment]
Ahh, so having "NATIONENEMIES" in the default config does nothing for me then, I see :) Thanks.

**Comment by jrbudda** [comment]
ooooh i see now, you had it typed into the default config, you explicitly said you ran /sentry target add in your initial post.

I may be able to make that possible in the defaults, have to take a look.

**Comment by NotYetRated** [comment]
Ahh I am sorry I did completely mislead you initially :) my bad there. Its not a huge deal, just one more thing I was not certain how exactly it worked. 
Thanks :)
