### ISSUE TITLE
Quick death Sentry

### ISSUE THREAD

**Issue by Mpa3ota** [jrbudda/Sentry#78]
Error in the following.
Created NPC Sentry Guard owner admin. Armor 10, life 20, attack 10, etc., generally the default settings.
Normal player kills this sentry 1 hit, not crit, nothing, just 1 hit for 10 units has damage. When the protection of lives and sentry player just can not get over it and will not cause any damage. What could it be? How to configure it?

**Comment by jrbudda** [comment]
Sounds like a plugin conflict.
