### ISSUE TITLE
Would be nice to have a seperate initial spawn from respawn time.

### ISSUE THREAD

**Issue by Talphin** [jrbudda/Sentry#79]
I set a sentry respawn to 3 minutes after death, but it also takes it 3 minutes to initially spawn when player enters the area. This gives the player more than enough time to get in, loot chest, and get out without ever even having to face the NPC. Would be nice if I could cause them to spawn instantly as soon as a player enters the area as long as he isn't already spawned, or wasn't recently killed (within the spawn after death time).

Maybe I am missing something? Is there a way to already do this?

**Comment by jrbudda** [comment]
Hmm, that's how it should be working already There's been some recently reported issues with NPC not spawning correctly with chunk load, could be related. I'll talk it over with the Citizens devs.

**Comment by jrbudda** [comment]
Build 656 of Citizens2 should clear this up.
