### ISSUE TITLE
0dmg knockback is ineffective

### ISSUE THREAD

**Issue by TerraNetworkOrg** [jrbudda/Sentry#8]
Hi jrbudda!

I mentioned a problem the last few days.
If a Sentries Armor is higher than the incoming damage he will block the damage but will knockbacked.
Yes this is a feature i know, but if the player spams his attacks the NPC has nearly 0 chance to hit the player what means he will be an easy target even with 10/10 Setting. It's enough the player does 2-4 damage every 10 or 15 hits, because the NPC gets knockbacked every time and can't hit back.

**Comment by jrbudda** [comment]
I'll make it so the force of the knockback is lessened by the amount of armor. Since an armored Sentry would be heavier.

**Comment by jrbudda** [comment]
I also realized I wasn't honoring the normal .5 second invulnerability between hits. I just tested it, between that and the scalable knockback, a fully armored sentry will advance (slowly) on a player no matter how much he spams attack.

**Comment by TerraNetworkOrg** [comment]
Great update, really hard fights now :-)

Could you make it possible to choose higher respawn values than 300 ?

**Comment by jrbudda** [comment]
OK.
