### ISSUE TITLE
Damage poblems

### ISSUE THREAD

**Issue by Ninjamuffin1** [jrbudda/Sentry#80]
Before the 1.5 update all my sentries worked flawlessly, but now I create a sentry default settings and i can hit them once with my fist and in the text it says [Npcname] died. It does not register the hit as the npc does not move when hit it just dies. I believe it might be a conflict with Ancient Rpg but I have no idea how to fix that.

**Comment by jrbudda** [comment]
1.5 of what?
And yes your problem is almost certainly a plugin conflict, try disabling ancient RPG to see if it goes away.
