### ISSUE TITLE
[Suggestion] Faction Sentries

### ISSUE THREAD

**Issue by jnqazwsx** [jrbudda/Sentry#81]
Some servers i play on has factions and of course citizens and the problem is that if you make an alliance on factions you have to update the target and ignore list for every sentry the faction has

**Comment by jrbudda** [comment]
yea that sounds about right.

**Comment by jnqazwsx** [comment]
So is it possible to make Sentries that has some kind of shared target and ignore list?

**Comment by jrbudda** [comment]
Nope. There's talk of a multi-select function for citizens though. That might help.
