### ISSUE TITLE
Copy npcs

### ISSUE THREAD

**Issue by hapsterfuzzray** [jrbudda/Sentry#82]
It would be cool if you could copy a npc and spawn another one with the exact same stats as the one before. The npc copy would be /npc copy and the spawn would be /npc copy spawn

**Comment by jrbudda** [comment]
Why can't you do this now?

**Comment by hapsterfuzzray** [comment]
I didn't see the copy thing on the wiki. Anyway, is there one?

**Comment by jrbudda** [comment]
http://wiki.citizensnpcs.com/Commands#NPC_Commands

**Comment by hapsterfuzzray** [comment]
Just a question. When you do npc copy, does it copy the sentry info and does it spawn right next to the npc you copied?

**Comment by hapsterfuzzray** [comment]
Also, when I copy and restart the server, all the copied npcs are gone

**Comment by jrbudda** [comment]
Are you sure the copies arent on top of the original? the spawn location get copied too.

**Comment by hapsterfuzzray** [comment]
Hmmmmm I think I have to check.
