### ISSUE TITLE
Target, Animals

### ISSUE THREAD

**Issue by NotYetRated** [jrbudda/Sentry#83]
I have a sentry set to target:

ENTITY:MONSTERS, EVENT:PVP, EVENT:PVNPC

My intent is to have guards only attack people who:
1. PvP other players
2. Attack other Citizens NPC's
3. Kill Monsters that come around.

When a player hits say, a chicken, the guard will kill the player. I do not want this. Have I mis-interpreted "EVENT:PVNPC"? or PVP?

**Comment by mcmonkey4eva** [comment]
"PVNPC" is wrong here. You should be using "PVSentry"
