### ISSUE TITLE
Sentry Greeting Not working.

### ISSUE THREAD

**Issue by Yandols** [jrbudda/Sentry#84]
Craftbukkit Version: 1.4.7-R02 (2608)
Citizens Version: 2.0.7 (build 672)
Sentry Version: 1.3.1 (1/19/2012)

I am having problems with the Sentry's Greeting. Existing Sentries that have greeting are functioning normally. But new Sentries that I create won't say a thing after I've set the greeting.

I created the sentry this way:
/npc create examplename
/trait sentry
/sentry greeting '<NPC>: Welcome to the Market area!'

**Comment by jrbudda** [comment]
Couple of possibilities: 
1) you need to set the warningrange >0 to turn warn/greet on
2) due to some recent optimizations it won't check the code for warn/greet if the sentry has no targets. In that case you should just use /npc text to make the sentry talk to nearby players.
