### ISSUE TITLE
Stormcaller targetting error

### ISSUE THREAD

**Issue by Totollie** [jrbudda/Sentry#86]
Hey, the stormcaller sentry works perfect except for one thing - when they hit a mob with lightning, they're obviously just calling a lightning effect. This means no mob actually ever targets them, making them practically invincible. Any solution to this?

**Comment by jrbudda** [comment]
Unfortunately no, there is no way to link the lightning damage back to the NPC to make mobs target it. Stormcallers are kinda meant to be used against players or for clearing out mobs from an area.
