### ISSUE TITLE
[Sugjestion] Priority Targeting

### ISSUE THREAD

**Issue by Matterom** [jrbudda/Sentry#88]
alter /sentry Target Add [Target] [Priority Integer]
Higher Priority means that if the Sentry Finds more than 1 target True, It will attack the target With The Highest Priority, Leaving it blank represents a priority lvl of 1 being the lowest, if the sentry finds he has all the same priority's Then the npc will target the closest to him.

**Comment by mcmonkey4eva** [comment]
@jrbudda - this is a fairly valid suggestion, why close it?
