### ISSUE TITLE
Factions Enemy

### ISSUE THREAD

**Issue by NemesisMate** [jrbudda/Sentry#89]
It would be great to have the equivalent of nationenemies but for factions.

It is very annoying to change all your guards to attack new ennemies or stop attacking old enemies. It would be great if them attack every actual enemies, just like nationenemies for Towny.

**Comment by jrbudda** [comment]
v1.3.4 should have this functionality. I don't run Factions so I didn't test it. let me know if there's any issues.

**Comment by NemesisMate** [comment]
Ok, I'll test it when I have time. Now I'm having another crash issue, I let it like a comment:

http://dev.bukkit.org/server-mods/sentry-citizens2/?comment=548
