### ISSUE TITLE
Sentries not attacking targets on their list?

### ISSUE THREAD

**Issue by abslodov** [jrbudda/Sentry#9]
Hello,

Just installed this, thanks so much for your work!

Question: any thoughts on why my sentry won't attack something on it's target list? I made it's range 100, warningrange 5 (to guard a door way), set his greeting (btw the command for greetings says 'greet' but /sentry greet doesn't work -- it's /sentry greeting), and I set his warning messages, equipped him, placed him statically, added both 'all' and 'entity:all' (wasn't sure what to type there)to his target list. I then logged in with another non-admin account, approached the npc, and his greeting message fired off, but no warning or attack....

**Comment by jrbudda** [comment]
Ah, there is a small typo checking for entity:all. Will be fixed in next build. Will also fix the help message.
Other targets should work.

**Comment by abslodov** [comment]
I found another reason!

If I manually set the owner of the npc to the server, instead of me, it works! I used myself, and entity:player as targets. With me as the owner it didn't work, server as owner I got my ass kicked :]
