### ISSUE TITLE
Server crash while using sentry

### ISSUE THREAD

**Issue by Dakado** [jrbudda/Sentry#90]
Hi, i Am using sentry 1.3.1, bukkit 1.4.7 and Citizens 2.0.7, when i create NPC everthing is ok, but when I try to /trait sentry is lags server and than my server crash....

No errors in console
Server running via multicraft

**Comment by XxCoolGamesxX** [comment]
It you test with nolagg plugin can say what is lag the in the server. We it more info of your crash.
