### ISSUE TITLE
Bodyguard Mode Does Not Deal Damage

### ISSUE THREAD

**Issue by TycheMoirae** [jrbudda/Sentry#91]
As the title said, Bodyguard mode does not deal damage for me (though the NPC does try to attack). While the Lookout mode is working fine. I checked the strength (thought it would changed when I change the mode) and it is 2. Mobs does not seem to "see" the NPC when in Bodyguard mode and won't attack it.

**Comment by Zeroi** [comment]
I have the same issue, he tries to hit but rarely does since he's looking at the player.

**Comment by jrbudda** [comment]
Bodyguards obey pvp protection so this is likely caused by another plugin.

**Comment by Zeroi** [comment]
That's not the issue. No PvP protection, only bodyguard, and he hits next to his target, because he's rotated, so his sword doesn't hit his target (not mobs either)
