### ISSUE TITLE
API Docs

### ISSUE THREAD

**Issue by jaxnb** [jrbudda/Sentry#92]
Can you please post an API for sentry? I am trying to program a plugin  and need the event called when a sentry kills a player. If I'm missing the API and it is already there, just point me to it.
Thanks.

**Comment by jrbudda** [comment]
Sentry doesn't call any events. Just listen for PlayerDeathEvent and check if killer.hasMetaData("NPC")

**Comment by jaxnb** [comment]
Thanks.
