### ISSUE TITLE
NPCs give error upon giving it the Sentry trait

### ISSUE THREAD

**Issue by Cynthia1337** [jrbudda/Sentry#99]
Whenever I make an NPC and give it the trait Sentry, it gives an error, upon opening the server log, I got this error:
http://pastebin.com/zRQayFcR

**Comment by XxCoolGamesxX** [comment]
The plugin is not update for 1.5.1 so only 1.5.

**Comment by jrbudda** [comment]
It is too updated for 1.5.1, get the latest version from the wiki

**Comment by XxCoolGamesxX** [comment]
You it not update the codes in the github. I look in your NMS is only work on the 1.5. The 1.5.1 use the .v1_5_R2 not the .v1_5_R1. I can update it for you. Oh you need a pom.xml be easy the update the codes at downloads the plugins one by one. Only need to change the codes in the pom.xml and update the plugins for you. It you need help for it i can make one for you. I'm a Dev too. My name in dev.bukkit is follet2004.

**Comment by jrbudda** [comment]
Sentry 1.3.3.2 is working for craftbukkit 1.5.1

**Comment by XxCoolGamesxX** [comment]
I now the codes on github is not update.
